### ISSUE TITLE
Add support for file level option

### ISSUE THREAD

**Issue by stocks29** [protobufjs/protobuf.js#1111]
protobuf.js version: 6.8.8

`Error: illegal token 'option'` is thrown when a file level `option` is specified. Per the spec, some options should be specified at the file level.

https://developers.google.com/protocol-buffers/docs/proto#options

To reproduce, create a proto file with a file level `option` and then use pbjs to try to convert it to json. It will: `Error: illegal token 'option'`

**Comment by alexander-fenster** [comment]
I had similar problem and I noticed it actually works if you put all your file-level options _before_ your services and messages.

Repro:

```js
const protobuf = require('protobufjs');
const result = protobuf.loadSync("test.proto");
console.log(result);
```

The contents of `test.proto` that works:

```protobuf
syntax = "proto3";

option go_package = "value"; // it works

message Test {
	int32 field = 1;
};
```

When loaded, it shows that the option was successfully parsed:

```
Root {
  options: { go_package: 'value' },
  ...
```

When I move this option after the message, it stops working. 

```protobuf
syntax = "proto3";

message Test {
	int32 field = 1;
};

option go_package = "value"; // DOES NOT WORK
```

```
/private/tmp/pbjs/node_modules/protobufjs/src/root.js:94
            throw err;
            ^

Error: illegal token 'option' (test.proto, line 7)
    at illegal (/private/tmp/pbjs/node_modules/protobufjs/src/parse.js:94:16)
    at parse (/private/tmp/pbjs/node_modules/protobufjs/src/parse.js:719:27)
    at process (/private/tmp/pbjs/node_modules/protobufjs/src/root.js:107:30)
    at fetch (/private/tmp/pbjs/node_modules/protobufjs/src/root.js:166:13)
    at Root.load (/private/tmp/pbjs/node_modules/protobufjs/src/root.js:194:13)
    at Root.loadSync (/private/tmp/pbjs/node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (/private/tmp/pbjs/node_modules/protobufjs/src/index-light.js:69:17)
    at Object.<anonymous> (/private/tmp/pbjs/index.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
```

This violates the protobuf 3 syntax defined [here](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec), according to which, an option can appear anywhere in the file:

```
proto = syntax { import | package | option | topLevelDef | emptyStatement }
topLevelDef = message | enum | service
```

Having that said, I suppose the correct title for this issue would be 'File-level options should be allowed anywhere in the proto file', or something like that. @stocks29 Does it make sense for you?
