### ISSUE TITLE
pbts does not work with Node 12.0

### ISSUE THREAD

**Issue by thomastoye** [protobufjs/protobuf.js#1212]
protobuf.js version: `protobufjs@6.8.8`

I tried generating a `.js` and `.d.ts` file using `pbjs` and `pbts`, but on node 12.0, `pbts` fails. Earlier versions of node work.

Node 12.0.0:

```
$ cat proto3.proto
syntax = "proto3";

message SearchRequest {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
}
$ npx pbjs -t static-module -w commonjs -o compiled.js proto2.proto
$ npx pbts -o compiled.d.ts compiled.js                            
/tmp/test/node_modules/protobufjs/cli/node_modules/requizzle/lib/requizzle.js:45
        if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
                       ^

TypeError: Cannot read property '0' of null
    at isNativeModule (/tmp/test/node_modules/protobufjs/cli/node_modules/requizzle/lib/requizzle.js:45:17)
    at Requizzle.requizzle (/tmp/test/node_modules/protobufjs/cli/node_modules/requizzle/lib/requizzle.js:82:6)
    at infectProxy (/tmp/test/node_modules/protobufjs/cli/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/tmp/test/node_modules/protobufjs/cli/node_modules/requizzle/lib/loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/tmp/test/node_modules/protobufjs/cli/node_modules/jsdoc/lib/jsdoc/fs.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Object.load (/tmp/test/node_modules/protobufjs/cli/node_modules/requizzle/lib/loader.js:112:15)
/tmp/test/node_modules/protobufjs/cli/pbts.js:133
                throw err;
                ^

Error: code 1
    at ChildProcess.<anonymous> (/tmp/test/node_modules/protobufjs/cli/pbts.js:130:27)
    at ChildProcess.emit (events.js:201:15)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
$ node --version
v12.0.0
$ npm list   
/tmp/test
└─┬ protobufjs@6.8.8
  ├── @protobufjs/aspromise@1.1.2
  ├── @protobufjs/base64@1.1.2
  ├── @protobufjs/codegen@2.0.4
  ├── @protobufjs/eventemitter@1.1.0
  ├─┬ @protobufjs/fetch@1.1.0
  │ ├── @protobufjs/aspromise@1.1.2 deduped
  │ └── @protobufjs/inquire@1.1.0 deduped
  ├── @protobufjs/float@1.0.2
  ├── @protobufjs/inquire@1.1.0
  ├── @protobufjs/path@1.1.2
  ├── @protobufjs/pool@1.1.0
  ├── @protobufjs/utf8@1.1.0
  ├── @types/long@4.0.0
  ├── @types/node@10.14.5
  └── long@4.0.0
```

Node 11.0.0:

```
$ nvm use 11.0
Now using node v11.0.0 (npm v6.4.1)
$ node --version
v11.0.0
$ npx pbjs -t static-module -w commonjs -o compiled.js proto2.proto
$ npx pbts -o compiled.d.ts compiled.js
```

I tried with a simple proto3 file and it has the same behaviour.

**Comment by dcodeIO** [comment]
I wonder where that [requizzle](https://www.npmjs.com/package/requizzle) dependency actually comes from. Doesn't look like a dependency I'd bet on.

**Comment by thomastoye** [comment]
ikr? It's not even in the tree:

```
$ npm list   
/tmp/test
└─┬ protobufjs@6.8.8
  ├── @protobufjs/aspromise@1.1.2
  ├── @protobufjs/base64@1.1.2
  ├── @protobufjs/codegen@2.0.4
  ├── @protobufjs/eventemitter@1.1.0
  ├─┬ @protobufjs/fetch@1.1.0
  │ ├── @protobufjs/aspromise@1.1.2 deduped
  │ └── @protobufjs/inquire@1.1.0 deduped
  ├── @protobufjs/float@1.0.2
  ├── @protobufjs/inquire@1.1.0
  ├── @protobufjs/path@1.1.2
  ├── @protobufjs/pool@1.1.0
  ├── @protobufjs/utf8@1.1.0
  ├── @types/long@4.0.0
  ├── @types/node@10.14.5
  └── long@4.0.0
```
It failed on CI for Node 12 and passed for Node 11, so it's not my machine.

**Comment by dcodeIO** [comment]
Seems to be a dependency of jsdoc, which `pbts` uses to parse the JS comments before transforming them to a TS definition.

**Comment by augustli2009** [comment]
same issue....... cost me almost 1 whole day.....roll back to 10.15.3 and everything is ok......

**Comment by warpy** [comment]
Correct me if I'm wrong but: a temporary solution to stay on node 12 is to manually add `jsdoc` > `3.5` (mine worked with `jsdoc@3.6.2`) to your dependencies. The "magic" @dcodeIO mentioned should allow this because it only cares that you have `^3.5.5` (notice the `^` range operator) version of jsdoc.

**Comment by fnlctrl** [comment]
I'm running node v12.13.0 on mac and everything is working fine for pbjs/pbts.

**Comment by dcodeIO** [comment]
Current support baseline is still Node.js v12, but that is pretty old by today's standards. Hence closing.
