### ISSUE TITLE
Error encoding a buffer

### ISSUE THREAD

**Issue by minemidnight** [protobufjs/protobuf.js#1225]
protobuf.js version: 6.88

Expected: No error
Recieved: Error

```js
const { body: { url: file } } = await superagent.get("https://random.dog/woof.json");
const { body: buffer } = await superagent.get(file);
```

trying to encode said buffer using something similar to.... (full code at https://github.com/oxylbot/message-handler)
```
syntax = "proto2";

message File {
    required string name = 1;
    required bytes file = 2;
}
```

error recieved:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:505:11)
    at BufferWriter.write_string_buffer [as string] (/app/node_modules/protobufjs/src/writer_buffer.js:68:22)
    at Type.Request$encode [as encode] (eval at Codegen (/app/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:7:16)
    at Type.encode_setup [as encode] (/app/node_modules/protobufjs/src/type.js:485:25)
    at Function.encode (/app/node_modules/protobufjs/src/message.js:56:23)
    at Service.rpcCall (/app/node_modules/protobufjs/src/rpc/service.js:96:78)
    at executor (/app/node_modules/@protobufjs/aspromise/index.js:44:16)
    at new Promise (<anonymous>)
    at Object.asPromise (/app/node_modules/@protobufjs/aspromise/index.js:28:12)
    at Service.rpcCall (/app/node_modules/protobufjs/src/rpc/service.js:86:21)
```

**Comment by minemidnight** [comment]
Sorry I'm just dumb. Works fine, was a problem with what was wrapping the File. Using a default value with required does not work though, not sure if thats intentional.
