### ISSUE TITLE
Error: illegal token '*/'

### ISSUE THREAD

**Issue by lili21** [protobufjs/protobuf.js#1237]
protobuf.js version: <6.8.8>

<please describe the expected and actual behavior>

```js
const protobuf = require('protobufjs')
const root = new protobuf.Root()
root.load('./test.proto', { alternateCommentMode: true }, (err, root) => {
  if (err) {
    throw err
  } else {
    console.log('success')
  }
})
```

```
Error: illegal token '*/' (/Users/li.li/just-do-it/try-pb-schema/test.proto, line 9)
    at illegal (/Users/li.li/just-do-it/try-pb-schema/node_modules/protobufjs/src/parse.js:94:16)
    at parse (/Users/li.li/just-do-it/try-pb-schema/node_modules/protobufjs/src/parse.js:734:23)
    at process (/Users/li.li/just-do-it/try-pb-schema/node_modules/protobufjs/src/root.js:107:30)
    at /Users/li.li/just-do-it/try-pb-schema/node_modules/protobufjs/src/root.js:182:17
    at fetchReadFileCallback (/Users/li.li/just-do-it/try-pb-schema/node_modules/@protobufjs/fetch/index.js:51:19)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

`test.proto`

```protobuf
syntax = "proto3";

message MyMessage {
  string name = 1;
  int32 age = 2;
}

// lklklklk
/*lilili
*/
```

It can't handle `/*...*/` comment under `//` comment.

**Comment by Yubiao-Li** [comment]
I'm having the same problem

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
