### ISSUE TITLE
Illegal name '}'

### ISSUE THREAD

**Issue by wcjohnson** [protobufjs/protobuf.js#1262]
protobuf.js version: 6.8.8

When parsing the following proto file from the Envoy proxy control plane:

https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/cds.proto

The following parsing error is thrown:

```
Error: illegal name '}' (/Users/wcj/dev/mesh/experiments/kube/gitops/protocols/envoy/api/v2/cds.proto, line 130)
    at illegal (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:94:16)
    at parseOptionValue (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:559:27)
    at parseOption (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:551:9)
    at parseInlineOptions (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:585:17)
    at parseField_line (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:376:13)
    at ifBlock (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:290:17)
    at parseField (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:366:9)
    at parseType_block (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:338:21)
    at ifBlock (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:286:17)
    at parseType (/Users/wcj/dev/mesh/experiments/kube/gitops/node_modules/protobufjs/src/parse.js:304:9)
```

The relevant lines of .proto code are:
```proto3
  // The timeout for new network connections to hosts in the cluster.
  google.protobuf.Duration connect_timeout = 4 [
    (validate.rules).duration.gt = {},
    (gogoproto.stdduration) = true,
    (gogoproto.nullable) = false
  ];
```

 It appears the parser is having difficulty with `(validate.rules).duration.gt = {}`. Removing the bracketed annotation resolves the parsing problem.

**Comment by wcjohnson** [comment]
This may be related to https://github.com/protobufjs/protobuf.js/issues/1142 as well. Both result from trying to load the Envoy control plane defs.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
