### ISSUE TITLE
TypeError: Cannot read property 'fromNumber' of undefined

### ISSUE THREAD

**Issue by ralphkocher** [protobufjs/protobuf.js#1279]
protobuf.js version: <please fill in>

<please describe the expected and actual behavior>
Actually my serverlogs are full of a unhandled promise rejection at protobuf which is used by a npm library:
```js
<please provide a code snippet for reproduction>
```
E 2019-08-15T13:52:57.069494812Z You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 
E 2019-08-15T13:52:57.069697571Z TypeError: Cannot read property 'fromNumber' of undefined
    at Field.resolve (/app/node_modules/protobufjs/src/field.js:289:38)
    at Type.setup (/app/node_modules/protobufjs/src/type.js:435:41)
    at Type.encode_setup [as encode] (/app/node_modules/protobufjs/src/type.js:485:17)
    at Type.LogEntry$encode [as encode] (eval at Codegen (/app/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:19:12)
    at Type.encode_setup [as encode] (/app/node_modules/protobufjs/src/type.js:485:25)
    at BundleDescriptor.getByteLength [as byteLengthFunction] (/app/node_modules/google-gax/build/src/grpc.js:250:28)
    at /app/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js:96:46
    at Array.forEach (<anonymous>)
    at BundleExecutor.schedule (/app/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js:95:22)
    at /app/node_modules/google-gax/build/src/bundlingCalls/bundleApiCaller.js:57:26
    at OngoingCallPromise.call (/app/node_modules/google-gax/build/src/call.js:82:27)
    at BundleApiCaller.call (/app/node_modules/google-gax/build/src/bundlingCalls/bundleApiCaller.js:56:16)
    at /app/node_modules/google-gax/build/src/createApiCall.js:84:30
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
 

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
