### ISSUE TITLE
AWS Lambda Compatible Statically Generated Code

### ISSUE THREAD

**Issue by ronak2121** [protobufjs/protobuf.js#1281]
protobuf.js version: 6.7.0

I'm trying to use the generated static code in a NodeJS 10.x AWS Lambda but I keep getting errors about syntax issues with the generated code.

Response:
{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Unexpected token *",
  "trace": [
    "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token *",
    "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:36:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:776:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}

The culprit seems to be the import line and the way the exports are defined.

/*eslint-disable block-scoped-var, id-length, no-control-regex, no-magic-numbers, no-prototype-builtins, no-redeclare, no-shadow, no-var, sort-vars*/
import * as $protobuf from "protobufjs/minimal";

// Common aliases
const $Reader = $protobuf.Reader, $util = $protobuf.util;

// Exported root namespace
const $root = $protobuf.roots["default"] || ($protobuf.roots["default"] = {});

Is there a way to generate any code that would be compatible with this environment?

**Comment by ronak2121** [comment]
Never mind; I got this to work; my problem was using the --es6 option; which isn't compatible with NodeJS 10.x.
