### ISSUE TITLE
parse fails to parse empty text options

### ISSUE THREAD

**Issue by mdouglass** [protobufjs/protobuf.js#1318]
protobuf.js version: 6.8.8

Envoy likes to use empty options blocks and protobuf.js blows up on them. For example:

```protobuf
google.protobuf.Duration timeout = 3 [(validate.rules).duration = {
    required: true
    gte {}
  }];
```
https://github.com/envoyproxy/envoy/blob/74a5a07d25c02f44aff2a154a6535c25ff23d292/api/envoy/api/v2/core/http_uri.proto#L47-50

```
Error: illegal name '}' (line 1)
    at illegal (/Users/matthew/gww/protobuf.js/src/parse.js:94:16)
    at parseOptionValue (/Users/matthew/gww/protobuf.js/src/parse.js:566:27)
    at parseOptionValue (/Users/matthew/gww/protobuf.js/src/parse.js:569:21)
    at parseOption (/Users/matthew/gww/protobuf.js/src/parse.js:553:9)
    at parseInlineOptions (/Users/matthew/gww/protobuf.js/src/parse.js:592:17)
    at parseField_line (/Users/matthew/gww/protobuf.js/src/parse.js:378:13)
    at ifBlock (/Users/matthew/gww/protobuf.js/src/parse.js:292:17)
    at parseField (/Users/matthew/gww/protobuf.js/src/parse.js:368:9)
    at parseType_block (/Users/matthew/gww/protobuf.js/src/parse.js:340:21)
    at ifBlock (/Users/matthew/gww/protobuf.js/src/parse.js:288:17)
```

**Comment by louiscryan** [comment]
Nudge - Hitting the same issue with the same protobufs :) Proposed PR seems stable.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
