### ISSUE TITLE
parser: doesn't support repeated option value

### ISSUE THREAD

**Issue by zonyitoo** [protobufjs/protobuf.js#1329]
protobuf.js version: 5.0.3

```protobuf
message MessageWithRepeatedOption {
    optional int32 value = 1 [(customized_option) = { in: [1, 2, 3] }];
}
```

We call it with `pbjs.main` (command line API).

```
Error: Error: no such Type or Enum 'mmgameauthadminweb.AddSubAuthSetResponse' in Type .mmgameauthadmindbmq.AddSubAuthSetResponse
    at Object.<anonymous> (/Users/littledu/WGFE/weadmin/backend/dist/helpers/apiManage/descGenerator.js:339:27)
    at step (/Users/littledu/WGFE/weadmin/backend/dist/helpers/apiManage/descGenerator.js:43:23)
    at Object.throw (/Users/littledu/WGFE/weadmin/backend/dist/helpers/apiManage/descGenerator.js:24:53)
    at rejected (/Users/littledu/WGFE/weadmin/backend/dist/helpers/apiManage/descGenerator.js:16:65)
```

The stacktrace isn't very useful. But after deleted `in: [1, 2, 3]` in `.proto` file, everything worked Ok.

Related code: https://github.com/protobufjs/protobuf.js/blob/master/src/parse.js#L556-L577 . It seems that parser doesn't handle `[` and `]`.

**Comment by natiz** [comment]
+1

**Comment by ZiyunHe** [comment]
+1

**Comment by ZiyunHe** [comment]
wrote a simple hack:

added new function:
`
function readArray() {
	var values = [];
        if (skip("[", true)) {
            do {
                var token = next();
                token = parseInt(token, 10);
                values.push(token);
            } while (skip(",", true));
            skip("]");
        }
        return values;
    }
`

change parseOptionValue function to following:
`
function parseOptionValue(parent, name) {
        if (skip("{", true)) { // { a: "foo" b { c: "bar" } }
            do {
                /* istanbul ignore if */
                if (!nameRe.test(token = next()))
                    throw illegal(token, "name");

                if (peek() === "{")
                    parseOptionValue(parent, name + "." + token);
                else {
                    skip(":");
                    if (peek() === "{")
                        parseOptionValue(parent, name + "." + token);
	            else if (peek() === "[") {  // here is the new change  <---
			setOption(parent, name + "." + token, readArray(true));
                    } else
                        setOption(parent, name + "." + token, readValue(true));
                }
                skip(",", true);
            } while (!skip("}", true));
        } else
            setOption(parent, name, readValue(true));
        // Does not enforce a delimiter to be universal
    }
`

**Comment by eyalpost** [comment]
The format for option is not JSON which is why `[` is invalid there. In your case, the option should have written like this:
```proto
message MessageWithRepeatedOption {
    optional int32 value = 1 [(customized_option) = { in: 1 in: 2 in: 3 }];
}
```
and altough the parser would not fail in this case, it will also not parse it correctly. There's a PR waiting for a long time now to be reviewed which fixes this: #1256

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
