### ISSUE TITLE
sparse fails when referencing a nested enum

### ISSUE THREAD

**Issue by meelapshah** [protobufjs/protobuf.js#1436]
protobuf.js version: 6.9.0 7fd2e182150

Referencing an enum defined in another message from another file causes --sparse to fail.

main.proto
```
syntax = "proto3";
import "lib.proto";
message Foo {
        NestedEnum x = 1;
}
```
lib.proto
```
syntax = "proto3";
message Bar {
        enum NestedEnum {
                A = 0;
        }
}
```

error:
```
$ ./bin/pbjs --path . --target static --sparse main.proto
/tmp/protobuf.js/cli/pbjs.js:244
            throw err;
            ^

Error: duplicate name 'Bar' in Root
    at Root.add (/tmp/protobuf.js/src/namespace.js:239:23)
    at /tmp/protobuf.js/cli/pbjs.js:291:32
    at traverse (/tmp/protobuf.js/cli/util.js:47:5)
    at /tmp/protobuf.js/cli/util.js:62:13
    at Array.forEach (<anonymous>)
    at Object.traverse (/tmp/protobuf.js/cli/util.js:61:29)
    at sparsify (/tmp/protobuf.js/cli/pbjs.js:275:14)
    at Object.main (/tmp/protobuf.js/cli/pbjs.js:237:17)
    at Object.<anonymous> (/tmp/protobuf.js/bin/pbjs:4:16)
```

**Comment by westhacker** [comment]
+1, any update for this issue?

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
