### ISSUE TITLE
No common namespace.

### ISSUE THREAD

**Issue by urgn** [protobufjs/protobuf.js#1438]
protobuf.js version: <please fill in>

I've a bunch of typescript services communicated over gRPC, I've decided to put the message descriptions into separate npm packages to be imported by the services they use. Also I've a lot of shared types between them. And the issue I met was that types from different packages can`t see each other in the internal grpc namespace.

```js
import { MyExtranalType } from "@urgn/grpc-messages-common";
import { Message, Type, Field } from "protobufjs/light";

@Type.d("MyInternalType")
export class MyInternalTypeextends Message<MyInternalType> {
    @Field.d(1, "string")
    url: string;

    @Field.d(1, "MyExtranalType")
    external:  MyExtranalType;
}
```

```
Error: no such Type or Enum 'MyExtranalType' in Type .MyInternalType
    at Type.lookupTypeOrEnum (/home/urgn/project/node_modules/@urgn/grpc-messages-content/node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (/home/urgn/project/node_modules/@urgn/grpc-messages-content/node_modules/protobufjs/src/field.js:265:94)
    at Type.setup (/home/urgn/project/node_modules/@urgn/grpc-messages-content/node_modules/protobufjs/src/type.js:435:41)
    at Type.decode_setup [as decode] (/home/urgn/project/node_modules/@urgn/grpc-messages-content/node_modules/protobufjs/src/type.js:507:17)
    at Function.decode (/home/urgn/project/node_modules/@urgn/grpc-messages-content/node_modules/protobufjs/src/message.js:81:23)
    at Object.requestDecoder (/home/urgn/project/src/rpc/contentService.js:134:75)
    at Object.deserialize (/home/urgn/project/node_modules/@urgn/grpc-server/src/GrpcServer.js:50:39)
    at /home/urgn/project/node_modules/grpc/src/server.js:584:33 {
  code: 13
}
```

I see that I probably can add imported declarations into a current namespace, but I have no Idea how to do that in a right way.
Something like:
```
getCurrentNamespace().add(MyExtranalType );
```

**Comment by urgn** [comment]
Now this is fixed by:
```js
import { util } from "protobufjs/light";

util.decorateType(MyExtranalType, 'MyExtranalType')
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
