### ISSUE TITLE
Failed at the protobufjs@6.10.1 postinstall script 'node scripts/postinstall'.

### ISSUE THREAD

**Issue by qohelet** [protobufjs/protobuf.js#1457]
protobuf.js version: 6.10.1
I'm trying to get a Hyperledger Fabric Example running: https://hyperledger-fabric.readthedocs.io/en/latest/tutorial/commercial_paper.html#application-dependencies 

```
(isabella)$ cd commercial-paper/organization/magnetocorp/application/
(isabella)$ npm install
```

Here's the command line output, the mentioned file is attached
[npm-debug.log](https://github.com/protobufjs/protobuf.js/files/4958775/npm-debug.log)
:
```
$ npm install
loadDep:js-yaml → resolve ▌ ╢██████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:js-yaml → resolve ▀ ╢██████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:winston → resolve ▌ ╢██████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:pkcs11js → reques ▌ ╢██████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:pkcs11js → afterA ▌ ╢██████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:protobufjs → 304  ▀ ╢██████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @grpc/grpc-js@1.0.3: wanted: {"node":"^8.13.0 || >=10.10.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:nano → get        ▌ ╢███████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:nano → resolveWit ▀ ╢███████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:universalify → 30 ▌ ╢███████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:request → get     ▄ ╢█████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
loadDep:request → resolve ▐ ╢█████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:uuid → get        ▀ ╢█████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:uri-js → afterAdd ▄ ╢█████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:asn1              ▌ ╢█████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDevDep:eslint → heade ▐ ╢██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:text-table → 200  ▄ ╢██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:text-table → reso ▄ ╢██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine doctrine@3.0.0: wanted: {"node":">=6.0.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine regexpp@2.0.1: wanted: {"node":">=6.5.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:text-table → addN ▐ ╢██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:text-table → reso ▌ ╢██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:text-table → reso ▌ ╢██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:text-table → addR ▀ ╢██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:resolve-from → re ▀ ╢██████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:callsites → reque ▌ ╢██████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:callsites → fetch ▐ ╢██████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:ansi-regex → addT ▀ ╢████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:ansi-regex → reso ▄ ╢██████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:string-width → he ▌ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:ansi-styles       ▀ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:strip-ansi → addT ▐ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> pkcs11js@1.0.21 install /home/schwaiger_m/Hyperledger/fabric-samples/commercial-paper/organization/magnetocorp/application/node_modules/pkcs11js
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-169-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/schwaiger_m/Hyperledger/fabric-samples/commercial-paper/organization/magnetocorp/application/node_modules/pkcs11js
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:pkcs11js@1.0.21 pkcs11js@1.0.21 install: `node-gyp rebuild`
npm WARN install:pkcs11js@1.0.21 Exit status 1

> protobufjs@6.10.1 postinstall /home/schwaiger_m/Hyperledger/fabric-samples/commercial-paper/organization/magnetocorp/application/node_modules/protobufjs
> node scripts/postinstall

sh: 1: node: not found
nodejs@1.0.0 /home/schwaiger_m/Hyperledger/fabric-samples/commercial-paper/organization/magnetocorp/application
├── @grpc/grpc-js@1.0.3  extraneous
├─┬ eslint@5.16.0 
│ ├─┬ @babel/code-frame@7.10.4 
│ │ └─┬ @babel/highlight@7.10.4 
│ │   ├── @babel/helper-validator-identifier@7.10.4 
│ │   └── js-tokens@4.0.0 
│ ├─┬ ajv@6.12.3 
│ │ ├── fast-deep-equal@3.1.3 
│ │ ├── fast-json-stable-stringify@2.1.0 
│ │ ├── json-schema-traverse@0.4.1 
│ │ └─┬ uri-js@4.2.2 
│ │   └── punycode@2.1.1 
│ ├─┬ chalk@2.4.2 
│ │ ├─┬ ansi-styles@3.2.1 
│ │ │ └─┬ color-convert@1.9.3 
│ │ │   └── color-name@1.1.3 
│ │ ├── escape-string-regexp@1.0.5 
│ │ └─┬ supports-color@5.5.0 
│ │   └── has-flag@3.0.0 
│ ├─┬ cross-spawn@6.0.5 
│ │ ├── nice-try@1.0.5 
│ │ ├── path-key@2.0.1 
│ │ ├── semver@5.7.1 
│ │ ├─┬ shebang-command@1.2.0 
│ │ │ └── shebang-regex@1.0.0 
│ │ └─┬ which@1.3.1 
│ │   └── isexe@2.0.0 
│ ├─┬ debug@4.1.1 
│ │ └── ms@2.1.2 
│ ├── doctrine@3.0.0 
│ ├─┬ eslint-scope@4.0.3 
│ │ ├── esrecurse@4.2.1 
│ │ └── estraverse@4.3.0 
│ ├── eslint-utils@1.4.3 
│ ├── eslint-visitor-keys@1.3.0 
│ ├─┬ espree@5.0.1 
│ │ ├── acorn@6.4.1 
│ │ └── acorn-jsx@5.2.0 
│ ├─┬ esquery@1.3.1 
│ │ └── estraverse@5.1.0 
│ ├── esutils@2.0.3 
│ ├─┬ file-entry-cache@5.0.1 
│ │ └─┬ flat-cache@2.0.1 
│ │   ├── flatted@2.0.2 
│ │   ├── rimraf@2.6.3 
│ │   └── write@1.0.3 
│ ├── functional-red-black-tree@1.0.1 
│ ├─┬ glob@7.1.6 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.6 
│ │ │ └── wrappy@1.0.2 
│ │ ├── inherits@2.0.4 
│ │ ├── once@1.4.0 
│ │ └── path-is-absolute@1.0.1 
│ ├── globals@11.12.0 
│ ├── ignore@4.0.6 
│ ├─┬ import-fresh@3.2.1 
│ │ ├─┬ parent-module@1.0.1 
│ │ │ └── callsites@3.1.0 
│ │ └── resolve-from@4.0.0 
│ ├── imurmurhash@0.1.4 
│ ├─┬ inquirer@6.5.2 
│ │ ├── ansi-escapes@3.2.0 
│ │ ├─┬ cli-cursor@2.1.0 
│ │ │ └─┬ restore-cursor@2.0.0 
│ │ │   ├─┬ onetime@2.0.1 
│ │ │   │ └── mimic-fn@1.2.0 
│ │ │   └── signal-exit@3.0.3 
│ │ ├── cli-width@2.2.1 
│ │ ├─┬ external-editor@3.1.0 
│ │ │ ├── chardet@0.7.0 
│ │ │ ├─┬ iconv-lite@0.4.24 
│ │ │ │ └── safer-buffer@2.1.2 
│ │ │ └─┬ tmp@0.0.33 
│ │ │   └── os-tmpdir@1.0.2 
│ │ ├── figures@2.0.0 
│ │ ├── mute-stream@0.0.7 
│ │ ├── run-async@2.4.1 
│ │ ├─┬ rxjs@6.6.0 
│ │ │ └── tslib@1.13.0 
│ │ ├─┬ string-width@2.1.1 
│ │ │ ├── is-fullwidth-code-point@2.0.0 
│ │ │ └─┬ strip-ansi@4.0.0 
│ │ │   └── ansi-regex@3.0.0 
│ │ ├─┬ strip-ansi@5.2.0 
│ │ │ └── ansi-regex@4.1.0 
│ │ └── through@2.3.8 
│ ├── json-stable-stringify-without-jsonify@1.0.1 
│ ├─┬ levn@0.3.0 
│ │ ├── prelude-ls@1.1.2 
│ │ └── type-check@0.3.2 
│ ├── lodash@4.17.19 
│ ├─┬ minimatch@3.0.4 
│ │ └─┬ brace-expansion@1.1.11 
│ │   ├── balanced-match@1.0.0 
│ │   └── concat-map@0.0.1 
│ ├─┬ mkdirp@0.5.5 
│ │ └── minimist@1.2.5 
│ ├── natural-compare@1.4.0 
│ ├─┬ optionator@0.8.3 
│ │ ├── deep-is@0.1.3 
│ │ ├── fast-levenshtein@2.0.6 
│ │ └── word-wrap@1.2.3 
│ ├── path-is-inside@1.0.2 
│ ├── progress@2.0.3 
│ ├── regexpp@2.0.1 
│ ├── semver@5.7.1 
│ ├─┬ strip-ansi@4.0.0 
│ │ └── ansi-regex@3.0.0 
│ ├── strip-json-comments@2.0.1 
│ ├─┬ table@5.4.6 
│ │ ├─┬ slice-ansi@2.1.0 
│ │ │ ├── astral-regex@1.0.0 
│ │ │ └── is-fullwidth-code-point@2.0.0 
│ │ └─┬ string-width@3.1.0 
│ │   ├── emoji-regex@7.0.3 
│ │   ├── is-fullwidth-code-point@2.0.0 
│ │   └─┬ strip-ansi@5.2.0 
│ │     └── ansi-regex@4.1.0 
│ └── text-table@0.2.0 
├─┬ fabric-ca-client@2.2.0 
│ ├─┬ fabric-common@2.2.0 
│ │ ├── callsite@1.0.0 
│ │ ├─┬ elliptic@6.5.3 
│ │ │ ├── bn.js@4.11.9 
│ │ │ ├── brorand@1.1.0 
│ │ │ ├── hash.js@1.1.7 
│ │ │ ├── hmac-drbg@1.0.1 
│ │ │ ├── minimalistic-assert@1.0.1 
│ │ │ └── minimalistic-crypto-utils@1.0.1 
│ │ ├── js-sha3@0.7.0 
│ │ ├─┬ nconf@0.10.0 
│ │ │ ├── async@1.5.2 
│ │ │ ├── ini@1.3.5 
│ │ │ ├── secure-keys@1.0.0 
│ │ │ └─┬ yargs@3.32.0 
│ │ │   ├── camelcase@2.1.1 
│ │ │   ├─┬ cliui@3.2.0 
│ │ │   │ ├─┬ strip-ansi@3.0.1 
│ │ │   │ │ └── ansi-regex@2.1.1 
│ │ │   │ └── wrap-ansi@2.1.0 
│ │ │   ├── decamelize@1.2.0 
│ │ │   ├─┬ os-locale@1.4.0 
│ │ │   │ └─┬ lcid@1.0.0 
│ │ │   │   └── invert-kv@1.0.0 
│ │ │   ├─┬ string-width@1.0.2 
│ │ │   │ ├── code-point-at@1.1.0 
│ │ │   │ └─┬ is-fullwidth-code-point@1.0.0 
│ │ │   │   └── number-is-nan@1.0.1 
│ │ │   ├── window-size@0.1.4 
│ │ │   └── y18n@3.2.1 
│ │ ├── promise-settle@0.3.0 
│ │ ├── sjcl@1.0.7 
│ │ └── yn@3.1.1 
│ ├── jsrsasign@8.0.20 
│ ├─┬ url@0.11.0 
│ │ ├── punycode@1.3.2 
│ │ └── querystring@0.2.0 
│ └─┬ winston@2.4.5 
│   ├── async@1.0.0 
│   ├── colors@1.0.3 
│   ├── cycle@1.0.3 
│   ├── eyes@0.1.8 
│   ├── isstream@0.1.2 
│   └── stack-trace@0.0.10 
├── fs-extra@9.0.1  extraneous
├─┬ js-yaml@3.14.0 
│ ├─┬ argparse@1.0.10 
│ │ └── sprintf-js@1.0.3 
│ └── esprima@4.0.1 
├── lodash.camelcase@4.3.0  extraneous
├── long@4.0.0  extraneous
└── nano@8.2.2  extraneous

npm WARN nodejs@1.0.0 No description
npm WARN nodejs@1.0.0 No repository field.
npm ERR! Linux 4.4.0-169-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! protobufjs@6.10.1 postinstall: `node scripts/postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the protobufjs@6.10.1 postinstall script 'node scripts/postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protobufjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protobufjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protobufjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/schwaiger_m/Hyperledger/fabric-samples/commercial-paper/organization/magnetocorp/application/npm-debug.log
[npm-debug.log](https://github.com/protobufjs/protobuf.js/files/4958771/npm-debug.log)

```

**Comment by qohelet** [comment]
[npm-debug.log](https://github.com/protobufjs/protobuf.js/files/4958777/npm-debug.log)

**Comment by qohelet** [comment]
Problem solved. 
Thank you Ubuntu. 

```
$ npm -version
3.5.2
```
