### ISSUE TITLE
Error parsing repeted field

### ISSUE THREAD

**Issue by haegemon** [protobufjs/protobuf.js#1469]
protobuf.js version: 6.10.1

<please describe the expected and actual behavior>
I tried to decode message but get a error. This message are sucessfully parsed on the server side and native client side. 

Proto file:
```
    message InternalProperties {
        message KeyValue {
            bytes key = 1;
            bytes value = 2;
        }

        repeated KeyValue list = 1;
    }
```

```js
const decodedString = 'ChsKB0JjZkd1aWQSEKk9HVHGQ+hEmzefCmrxENwKHwoLQmNmVmlld0d1aWQSEDJV2k4Aa/S3GAl1z64sILY='; // base64encoded string

const enc = new TextEncoder(); // always utf-8
const possibleError = IssueProtobuf.InternalProperties.verify(enc.encode(atob(value))); // null, no error
const result = InternalProperties.decode(enc.encode(atob(value))); // Error 
```

```
"Error: invalid wire type 7 at offset 38
    at Reader.skipType (webpack-internal:///./node_modules/protobufjs/src/reader.js:377:19)
    at Reader.skipType (webpack-internal:///./node_modules/protobufjs/src/reader.js:368:22)
    at Reader.skipType (webpack-internal:///./node_modules/protobufjs/src/reader.js:368:22)
    at Function.decode (webpack-internal:///./src/protobuf/Message.js:5240:22)
    at Function.decode (webpack-internal:///./src/protobuf/Message.js:5169:71)
    at Issue.unpackInternalProperties (webpack-internal:///./src/models/Issue.ts:137:117)
    at new Issue (webpack-internal:///./src/models/Issue.ts:80:10)
    at eval (webpack-internal:///./src/storage/projectIssues.storage.ts:73:20)
    at arrayMap (webpack-internal:///./node_modules/lodash/lodash.js:639:23)
    at Function.map (webpack-internal:///./node_modules/lodash/lodash.js:9580:14)"
```

**Comment by webmaster128** [comment]
Your 
```js
const value = 'ChsKB0JjZkd1aWQSEKk9HVHGQ+hEmzefCmrxENwKHwoLQmNmVmlld0d1aWQSEDJV2k4Aa/S3GAl1z64sILY=';```

looks good:

```
echo 'ChsKB0JjZkd1aWQSEKk9HVHGQ+hEmzefCmrxENwKHwoLQmNmVmlld0d1aWQSEDJV2k4Aa/S3GAl1z64sILY=' | base64 -d | protoc --decode_raw 
1 {
  1: "BcfGuid"
  2: "\251=\035Q\306C\350D\2337\237\nj\361\020\334"
}
1 {
  1: "BcfViewGuid"
  2: "2U\332N\000k\364\267\030\tu\317\256, \266"
}
```

but `new TextEncoder().encode(atob(value))` is not a correct way to base64 decode binary data. `new TextEncoder().encode(atob(value)).length` is 75, which differs from `echo 'ChsKB0JjZkd1aWQSEKk9HVHGQ+hEmzefCmrxENwKHwoLQmNmVmlld0d1aWQSEDJV2k4Aa/S3GAl1z64sILY=' | base64 -d | wc -c` (62).

**Comment by haegemon** [comment]
Thank you very much. I spent a day trying to find a bug inside protobufjs, but with your help i solved my problem in a hour
