### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Velortex** [protobufjs/protobuf.js#1490]
protobuf.js version: 6.10.1

If the bot runs for a while the error occurs
```js
let encoded = settings;
      if (protobuf) {
        let message = protobuf.create(settings);
        encoded = protobuf.encode(message);
      }
      this.steamUser.sendToGC(appid, header, proto, protobuf ? encoded.finish() : encoded);
```

Stack trace:
```
2020-09-17T17:16:22: RangeError: Maximum call stack size exceeded
2020-09-17T17:16:22:     at Type.create (/home/demonic/node_modules/protobufjs/src/type.js:421:12)
2020-09-17T17:16:22:     at /home/demonic/helpers/GameCoordinator.js:144:32
2020-09-17T17:16:22:     at new Promise (<anonymous>)
2020-09-17T17:16:22:     at GameCoordinator.sendMessage (/home/demonic/helpers/GameCoordinator.js:91:12)
2020-09-17T17:16:22:     at OverwatchBot.doOverwatchCase (/home/demonic/bot.js:314:42)
2020-09-17T17:16:22:     at OverwatchBot.<anonymous> (/home/demonic/bot.js:105:12)
2020-09-17T17:16:22:     at OverwatchBot.emit (events.js:314:20)
2020-09-17T17:16:22:     at OverwatchBot.doOverwatchCase (/home/demonic/bot.js:305:12)
2020-09-17T17:16:22:     at OverwatchBot.<anonymous> (/home/demonic/bot.js:105:12)
2020-09-17T17:16:22:     at OverwatchBot.emit (events.js:314:20)
2020-09-17T17:16:22:     at OverwatchBot.doOverwatchCase (/home/demonic/bot.js:305:12)
2020-09-17T17:16:22:     at OverwatchBot.<anonymous> (/home/demonic/bot.js:105:12)
2020-09-17T17:16:22:     at OverwatchBot.emit (events.js:314:20)
2020-09-17T17:16:22:     at OverwatchBot.doOverwatchCase (/home/demonic/bot.js:305:12)
2020-09-17T17:16:22:     at OverwatchBot.<anonymous> (/home/demonic/bot.js:105:12)
2020-09-17T17:16:22:     at OverwatchBot.emit (events.js:314:20)
```

**Comment by Velortex** [comment]
my own fault
