### ISSUE TITLE
`allow_alias` option for enums should work regardless of where it appears in an enum definition

### ISSUE THREAD

**Issue by doeg** [protobufjs/protobuf.js#1521]
protobuf.js version: 6.10.2

**Expected behavior:** 
The `allow_alias` option for enums should work regardless of its order in the enum proto definition.

**Actual behavior:**
`pbjs` compilation fails with a `duplicate id` error when `option allow_alias` appears _after_ the first duplicate ID in a proto definition. 

The proto3 spec describes the grammar for enums: https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#enum_definition However, it does not specify that options should come in a particular order:

```
enum = "enum" enumName enumBody
enumBody = "{" { option | enumField | emptyStatement } "}"
enumField = ident "=" [ "-" ] intLit [ "[" enumValueOption { ","  enumValueOption } "]" ]";"
enumValueOption = optionName "=" constant
```

Further, `protoc` is able to correctly compile enums with duplicate IDs regardless of where `allow_alias` appears in the enum definition. 

# How to reproduce

❌  First, we consider our base case: an _expected_ failure when we have duplicate IDs _without_ the `allow_alias` option. The following .proto file maps two IDs, `DOG` and `PUPPY`, to the same value:

```proto
syntax = "proto3";

enum TestEnum {
	DOG = 0;
	CAT = 1;
	PUPPY = 0;
	RAT = 2;
}
```

Since we don't specify the `allow_alias` option, compilation fails as expected:

```bash
$ ./node_modules/.bin/pbjs test.proto
/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/cli/pbjs.js:244
            throw err;
            ^

Error: duplicate id 0 in Enum TestEnum
    at Enum.add (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/enum.js:133:19)
    at parseEnumValue (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:534:16)
    at parseEnum_block (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:507:15)
    at ifBlock (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:290:17)
    at parseEnum (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:495:9)
    at parseCommon (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:265:17)
    at parse (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:757:21)
    at process (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/root.js:127:30)
    at fetch (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/root.js:178:13)
    at Root.load (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/root.js:206:13)
```

✅ If we add the `allow_alias` option to the _top_ of `TestEnum`, compilation succeeds:

```proto
syntax = "proto3";

enum TestEnum {
	option allow_alias = true;
	DOG = 0;
	CAT = 1;
	PUPPY = 0;
	RAT = 2;
}
```

```
$ ./node_modules/.bin/pbjs test.proto
{
  "nested": {
    "TestEnum": {
      "options": {
        "allow_alias": true
      },
      "values": {
        "DOG": 0,
        "CAT": 1,
        "PUPPY": 0,
        "RAT": 2
      }
    }
  }
}
```

✅ Indeed, compilation succeeds no matter where we put the option, as long as it comes _before_ a duplicate/aliased ID:

```proto
syntax = "proto3";

enum TestEnum {
	DOG = 0;
	CAT = 1;
	option allow_alias = true;
	PUPPY = 0;
	RAT = 2;
}
```

```bash
$ ./node_modules/.bin/pbjs test.proto
{
  "nested": {
    "TestEnum": {
      "options": {
        "allow_alias": true
      },
      "values": {
        "DOG": 0,
        "CAT": 1,
        "PUPPY": 0,
        "RAT": 2
      }
    }
  }
}
```

❌ However, putting `allow_alias` after a duplicate ID throws a compilation error:

```proto
syntax = "proto3";

enum TestEnum {
	DOG = 0;
	CAT = 1;
	PUPPY = 0;
	option allow_alias = true;
	RAT = 2;
}
```

```
$ ./node_modules/.bin/pbjs test.proto
/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/cli/pbjs.js:244
            throw err;
            ^

Error: duplicate id 0 in Enum TestEnum
    at Enum.add (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/enum.js:133:19)
    at parseEnumValue (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:534:16)
    at parseEnum_block (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:507:15)
    at ifBlock (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:290:17)
    at parseEnum (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:495:9)
    at parseCommon (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:265:17)
    at parse (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/parse.js:757:21)
    at process (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/root.js:127:30)
    at fetch (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/root.js:178:13)
    at Root.load (/Users/sbainbridge/workspace/protobuf-allow_alias_bug/node_modules/protobufjs/src/root.js:206:13)
```

## Counter-example: protoc

`protoc` successfully compiles no matter where `allow_alias` appears:

```proto
syntax = "proto3";

enum TestEnum {
	DOG = 0;
	CAT = 1;
	PUPPY = 0;
	option allow_alias = true;
	RAT = 2;
}
```

```bash
$ protoc --js_out=import_style=commonjs,binary:. test.proto

$ cat test_pb.js 
// source: test.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.TestEnum', null, global);
/**
 * @enum {number}
 */
proto.TestEnum = {
  DOG: 0,
  CAT: 1,
  PUPPY: 0,
  RAT: 2
};

goog.object.extend(exports, proto);
```

**Comment by xflcx1991** [comment]
It's been 6 years, and this issue is still open, alas
