### ISSUE TITLE
Error: illegal value ';'

### ISSUE THREAD

**Issue by dwj-AA** [protobufjs/protobuf.js#1534]
protobuf.js version: <6.10.2>

actual: 
UnhandledPromiseRejectionWarning: Error: illegal name ';'
expect:
parse option correct

```js
option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
    host: "xxxxx";
    info: {
        title: "xxxxxxx";
        version: "xxxxx";
        description: "xxxxxx";
    };
    schemes: HTTP;
    schemes: HTTPS;
    consumes: "application/json";
    produces: "application/json";
};
```

```
UnhandledPromiseRejectionWarning: Error: illegal name ';' (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/protos/channel_backend/channel_backend.proto, line 22)
    at illegal (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/src/parse.js:96:16)
    at parseOptionValue (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/src/parse.js:570:27)
    at parseOption (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/src/parse.js:560:27)
    at parse (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/src/parse.js:750:17)
    at process (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/src/root.js:127:30)
    at fetch (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/src/root.js:178:13)
    at Root.load (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/src/root.js:206:13)
    at Root.loadSync (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/src/root.js:247:17)
    at main (/Users/duwenjie/dwj/laiye-repos/laiye-remote/packages/web/node_modules/protobufjs/cli/pbjs.js:235:18)
    at internal/util.js:278:30
(node:87401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:87401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by alexisvisco** [comment]
2022 same issue ...

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
