### ISSUE TITLE
Error in enum in imported file not reported when file is synchronously loaded

### ISSUE THREAD

**Issue by dm185016** [protobufjs/protobuf.js#1544]
protobuf.js version: 6.10.2

Given the following in an import file, I expect an exception to be thrown:

> message CommomBitMapDetails
> {
>     int32 station = 1;
>     int32 width = 2;
>     int32 alignment = 3;
>     enum BitMapType {
>         PTR_BMT_BMP = 1;
>         PTR_BMT_JPEG = 2:
>         PTR_BMT_GIF = 3:
>     }
>     BitMapType type = 4;
> }
> 

Notice that the lines containing PTR_BMT_JPEG and PTR_BMT_GIF end with ':' and not ';'.  I debugged through the source code and found that the error was thrown but was swallowed and not reflected back to the loadSync operation, falsely causing me to think that it loaded properly.

```js
        try {
            var fn = path.join(scriptDir, './proto/POSPrinterMessageCollection.proto');
            sdk.log.info('Loading prototypes:  ', fn);
            this.root = proto.loadSync(fn);
            DefaultReceipt.root = this.root;
        }
        catch (exc) {
            sdk.log.error(exc.message);
            sdk.log.error(exc.stack);
            throw exc;
        }
        this._FileBitMapType = this._root.lookupType("POSPrinterMessages.FileBitMap");
        this._MemoryBitMapType = this._root.lookupType("POSPrinterMessages.MemoryBitMap");

```

```
No error was detected during the loadSync operation.  The assignment to this._FileBitMapType fails saying:

      tbsdk: 02/03 14:41:47.831 1612381307831 error: no such type: POSPrinterMessages.FileBitMap
      tbsdk: 02/03 14:41:48.526 1612381308526 error: Error: no such type: POSPrinterMessages.FileBitMap
          at Root.lookupType (E:\Source\scox\scoxdoc\node_modules\protobufjs\src\namespace.js:382:15)
          at Function.set root [as root] (E:\Source\scox\scoxdoc\dist\devices\printers\DefaultReceipt.js:68:43)
   ...
r.js:138:18)


```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
