### ISSUE TITLE
illegal token '-'

### ISSUE THREAD

**Issue by fupengl** [protobufjs/protobuf.js#1551]
protobuf.js version: <please fill in>

<please describe the expected and actual behavior>

```js
    "protobufjs": "6.10.2",
```

```
Build proto/qrobot.proto error:  Error: illegal token '-' (proto/qrobot.proto, line 4092)
    at illegal (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/parse.js:96:16)
    at parse (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/parse.js:763:23)
    at process (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/root.js:127:30)
    at fetch (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/root.js:178:13)
    at GoogleProtoFilesRoot.load (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/root.js:206:13)
    at GoogleProtoFilesRoot.loadSync (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/root.js:247:17)
    at loadSync (/Users/fupeng/Workspace/github/stan/node_modules/google-proto-files/build/src/load.js:69:17)
    at writeDTS (/Users/fupeng/Workspace/github/stan/packages/proto-gen-dts/lib/write-dts.js:219:45)
    at protoGenDTS (/Users/fupeng/Workspace/github/stan/packages/proto-gen-dts/lib/gen-dts.js:72:41)
    at Object.<anonymous> (/Users/fupeng/Workspace/github/stan/packages/proto-gen-dts/lib/cli.js:67:23)

```

**Comment by fupengl** [comment]
> protobuf.js version:
> 
> ```js
>     "protobufjs": "6.10.2",
> ```
> 
> ```
> Build proto/qrobot.proto error:  Error: illegal token '-' (proto/qrobot.proto, line 4092)
>     at illegal (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/parse.js:96:16)
>     at parse (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/parse.js:763:23)
>     at process (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/root.js:127:30)
>     at fetch (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/root.js:178:13)
>     at GoogleProtoFilesRoot.load (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/root.js:206:13)
>     at GoogleProtoFilesRoot.loadSync (/Users/fupeng/Workspace/github/stan/node_modules/protobufjs/src/root.js:247:17)
>     at loadSync (/Users/fupeng/Workspace/github/stan/node_modules/google-proto-files/build/src/load.js:69:17)
>     at writeDTS (/Users/fupeng/Workspace/github/stan/packages/proto-gen-dts/lib/write-dts.js:219:45)
>     at protoGenDTS (/Users/fupeng/Workspace/github/stan/packages/proto-gen-dts/lib/gen-dts.js:72:41)
>     at Object.<anonymous> (/Users/fupeng/Workspace/github/stan/packages/proto-gen-dts/lib/cli.js:67:23)
> ```

use this `alternateCommentMode: true` to throw an error

**Comment by fupengl** [comment]
![image](https://user-images.githubusercontent.com/20211964/109780552-15c74a00-7c42-11eb-8761-90ea1cc337ff.png)

**Comment by hugebdu** [comment]
+1

**Comment by fupengl** [comment]
Can you help?
