### ISSUE TITLE
No float in protobufjs for GTFS-Realtime with express.js and axios.js

### ISSUE THREAD

**Issue by dancesWithCycles** [protobufjs/protobuf.js#1553]
protobuf.js version: ```"protobufjs": "^6.10.2"```

Hi folks,
I hope this finds you well. I thank the protobufjs comunity for this awesome library. Recently I am using it in an ```express.js``` server and ```axios.js``` client to transmit a GTFS-Realtime message.
Anyhow, the transmission, with encoding, POST, decoding, encoding, GET, decoding, only works as long as I omit the ```Position``` message that contains ```float``` fields. Do you think this is due to an encoding/decoding issue or rather due to automagical data transformation during transmission?

This is the express.js server:
```
const express = require('express');
const protobuf = require('protobufjs');
const debug=require('debug')('xpress');

const app = express();

run().catch(err => {
    debug('run error')
    console.log(err)
});

async function run() {

    const protoFile=__dirname+'/gtfs-realtime.proto';
    debug('protofile: %s',protoFile)
    
    //async load of protobuf file
    const root = await protobuf.load(protoFile);

    // Obtain message types
    const FeedMessage = root.lookupType("transit_realtime.FeedMessage");
    const FeedHeader = root.lookupType("transit_realtime.FeedHeader");
    const FeedEntity = root.lookupType("transit_realtime.FeedEntity");
    const VehiclePosition = root.lookupType("transit_realtime.VehiclePosition");
    const Position = root.lookupType("transit_realtime.Position");

    var pos = Position.create({latitude:36,longitude:-79});
    debug('pos created')
    
    //TODO Why does Position msg not work? Is it converted on transmission?
//ERROR    var vehiclePosition = VehiclePosition.create({position:pos});
    var vehiclePosition = VehiclePosition.create();
    debug('vehiclePosition created')

    var feedEntity = FeedEntity.create({id:'uuid-xpress',
    vehicle:vehiclePosition});
    debug('feedEntity created')

    var feedHeader = FeedHeader.create({gtfsRealtimeVersion:'2.0',
    incrementality:0});
    debug('feedHeader created')

    var feedMessage = FeedMessage.create({header:feedHeader,
    entity:[feedEntity]});
    debug('feedMessage created')
    debug("JSON: %s", JSON.stringify(feedMessage));

    // Verify the payload if necessary (i.e. when possibly incomplete or invalid)
    var errMsg = FeedMessage.verify(feedMessage);
    if (errMsg){
        debug('feedMessage invalid')
        throw Error(errMsg);
    }else{
        debug('feedMessage valid')
    }

    var encodedFeedMsg = FeedMessage.encode(feedMessage).finish();
    debug('feedMessage encoded')

    app.get('/user', function(req, res) {
	debug('req.url %s',req.url)
	debug('req.method %s',req.method)
	debug('req.headers %s',JSON.stringify(req.headers))
	//res.send(User.encode(user).finish());
//TODO ?	res.send(encodedFeedMsg);
	res.type('application/octet-stream').send(encodedFeedMsg);
	// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ might not be necessary
    });
  
//TODO ?    app.post('/user', function(req, res) {
    app.post('/user', express.text({ type: '*/*' }), function(req, res) {
	debug('req.url %s',req.url)
	debug('req.method %s',req.method)
	debug('req.headers %s',JSON.stringify(req.headers))
	// Assume `req.body` contains the protobuf as a utf8-encoded string
	const user = FeedMessage.decode(Buffer.from(req.body));
	debug('req.body decoded: %s',JSON.stringify(user));
	res.end();
    });
    
    await app.listen(3000);
  
} 
```

This is the axios.js client:
```
const axios = require('axios');
const protobuf = require('protobufjs');
const debug=require('debug')('axios');

run().catch(err => {
    debug('run: error')
    console.log(err)
});

async function run() {
    debug('run:...')

    const protoFile=__dirname+'/gtfs-realtime.proto';
    debug('protofile: %s',protoFile)

    //async load of protobuf file
    const root = await protobuf.load(protoFile);
    //const User = root.lookupType('userpackage.User');
    const FeedMessage = root.lookupType("transit_realtime.FeedMessage");

    //HTTP GET
    let dataGet = await axios.get('http://localhost:3000/user')
	.then(res => res.data);
    debug('data received via GET');
    debug('decoded data from GET: ', FeedMessage.decode(Buffer.from(dataGet)));

    //HTTP POST
    const FeedHeader = root.lookupType("transit_realtime.FeedHeader");
    const FeedEntity = root.lookupType("transit_realtime.FeedEntity");
    const VehiclePosition = root.lookupType("transit_realtime.VehiclePosition");
    const Position = root.lookupType("transit_realtime.Position");

    var pos = Position.create({latitude:37.79192,longitude:-122.39087});
    debug('pos created')
    debug("pos JSON: %s", JSON.stringify(pos));

    //TODO Why does Position msg not work? Is it converted on transmission?
//ERROR    var vehiclePosition = VehiclePosition.create({position:pos});
    var vehiclePosition = VehiclePosition.create();
    debug('vehiclePosition created')

    var feedEntity=FeedEntity.create({id:'uuid-axios',vehicle:vehiclePosition});
    debug('feedEntity created')

    var feedHeader = FeedHeader.create({gtfsRealtimeVersion:'2.0',
    incrementality:0});
    debug('feedHeader created')

    var feedMessage = FeedMessage.create({header:feedHeader,entity:[feedEntity,feedEntity]});
    debug('feedMessage created')
    debug("JSON: %s", JSON.stringify(feedMessage));

    // Verify the payload if necessary (i.e. when possibly incomplete or invalid)
    var errMsg = FeedMessage.verify(feedMessage);
    if (errMsg){
        debug('feedMessage invalid')
        throw Error(errMsg);
    }else{
        debug('feedMessage valid')
    }

    const encodedPost=FeedMessage.encode(feedMessage).finish();
    debug('POST encoded');
    //url as first,
    //request body as second and
    //options as third  POST argument
    //response is returned
    const res=await axios.post(
	'http://localhost:3000/user',
	encodedPost,{
	    headers:{
		'content-type':'application/octet-stream'},
	    //		'content-type':'application/x-protobuf'}
	    'transformRequest':[]
	}
    ).then(res => res.data);
    debug('POST sent');
    debug('res JSON: %s',JSON.stringify(res));
    //debug('res content-type: %s',res.data.headers['content-type']);

} 
```

When I include the ```Position``` msg I receive the following error:
```
rs
[nodemon] starting `node index.js`
  axios run:... +0ms
  axios protofile: /home/user/Desktop/sandbox/protobufjs/axios-msg-gtfs-rt/gtfs-realtime.proto +3ms
  axios data received via GET +76ms
  axios run: error +18ms
RangeError: index out of range: 42 + 10 > 42
    at indexOutOfRange (/home/user/Desktop/sandbox/protobufjs/axios-msg-gtfs-rt/node_modules/protobufjs/src/reader.js:13:12)
    at BufferReader.read_uint32 [as uint32] (/home/user/Desktop/sandbox/protobufjs/axios-msg-gtfs-rt/node_modules/protobufjs/src/reader.js:98:19)
    at Type.FeedMessage$decode [as decode] (eval at Codegen (/home/user/Desktop/sandbox/protobufjs/axios-msg-gtfs-rt/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:8:11)
    at Type.decode_setup [as decode] (/home/user/Desktop/sandbox/protobufjs/axios-msg-gtfs-rt/node_modules/protobufjs/src/type.js:507:25)
    at run (/home/user/Desktop/sandbox/protobufjs/axios-msg-gtfs-rt/index.js:25:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[nodemon] clean exit - waiting for changes before restart
```
I would be very thankful for any little advice.

Cheers!

**Comment by dancesWithCycles** [comment]
Although I am facing the risk of answering my issue by myself, I want to share the following experiment. I made up this .proto file on my own:
```
package userpackage;
syntax = "proto3";

message User {
  string name = 1;
  int32 age = 2;
  float temperature = 3;
```

I am using this express.js server:
```
const express = require('express');
const protobuf = require('protobufjs');
const debug=require('debug')('xpress');

const app = express();

run().catch(err => {
    debug('run error')
    console.log(err)
});

async function run() {

    const protoFile=__dirname+'/user.proto';
    debug('protofile: %s',protoFile)
    //async load of protobuf file
    const root = await protobuf.load(protoFile);
    const User = root.lookupType('userpackage.User');

    const user = { name: 'Bill', age: 30, temperature: 36.3 };
    debug('user: %s',JSON.stringify(user))

    app.get('/user', function(req, res) {
	debug('req.url %s',req.url)
	debug('req.method %s',req.method)
	debug('req.headers %s',JSON.stringify(req.headers))
	res.send(User.encode(user).finish());
    });
  
    app.post('/user', express.text({ type: '*/*' }), function(req, res) {
	debug('req.url %s',req.url)
	debug('req.method %s',req.method)
	debug('req.headers %s',JSON.stringify(req.headers))
	// Assume `req.body` contains the protobuf as a utf8-encoded string
	const user = User.decode(Buffer.from(req.body));
	debug('req.body decoded: %s',JSON.stringify(user));
	res.end();
    });
    
    await app.listen(3000);
  
} 
```

I am using this axios.js client:
```
const axios = require('axios');
const protobuf = require('protobufjs');
const debug=require('debug')('axios');

run().catch(err => {
    debug('run: error')
    console.log(err)
});

async function run() {
    debug('run:...')

    const protoFile=__dirname+'/user.proto';
    debug('protofile: %s',protoFile)

    //async load of protobuf file
    const root = await protobuf.load(protoFile);
    const User = root.lookupType('userpackage.User');

    //HTTP GET
    let dataGet = await axios.get('http://localhost:3000/user')
	.then(res => res.data);
    debug('data received via GET');
    debug('decoded data from GET', User.decode(Buffer.from(dataGet)));

    //HTTP POST
    const dataPost = { name: 'Joe', age: 27, temperature: 36.7 };
    debug('data for POST: %s',JSON.stringify(dataPost))
    const encodedPost = User.encode(dataPost).finish();
    debug('POST encoded');
    await axios.post('http://localhost:3000/user', encodedPost).
    then(res => res.data);
    debug('POST sent');
} 
```

I am facing this error:
```
[nodemon] starting `node index.js`
  xpress protofile: /home/user/Desktop/sandbox/protobufjs/express-msg-usr/user.proto +0ms
  xpress user: {"name":"Bill","age":30,"temperature":36.3} +16ms
  xpress req.url /user +12s
  xpress req.method GET +1ms
  xpress req.headers {"accept":"application/json, text/plain, */*","user-agent":"axios/0.21.1","host":"localhost:3000","connection":"close"} +0ms
  xpress req.url /user +60ms
  xpress req.method POST +0ms
  xpress req.headers {"accept":"application/json, text/plain, */*","content-type":"application/x-www-form-urlencoded","user-agent":"axios/0.21.1","content-length":"12","host":"localhost:3000","connection":"close"} +0ms
Error: invalid wire type 7 at offset 15
    at BufferReader.Reader.skipType (/home/user/Desktop/sandbox/protobufjs/express-msg-usr/node_modules/protobufjs/src/reader.js:377:19)
    at Type.User$decode [as decode] (eval at Codegen (/home/user/Desktop/sandbox/protobufjs/express-msg-usr/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:20:5)
    at /home/user/Desktop/sandbox/protobufjs/express-msg-usr/index.js:35:20
    at Layer.handle [as handle_request] (/home/user/Desktop/sandbox/protobufjs/express-msg-usr/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/user/Desktop/sandbox/protobufjs/express-msg-usr/node_modules/express/lib/router/route.js:137:13)
    at /home/user/Desktop/sandbox/protobufjs/express-msg-usr/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/user/Desktop/sandbox/protobufjs/express-msg-usr/node_modules/raw-body/index.js:224:16)
    at done (/home/user/Desktop/sandbox/protobufjs/express-msg-usr/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/user/Desktop/sandbox/protobufjs/express-msg-usr/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:203:15)
```
After running through this experiment I believe my issue is rather due to a automagical data transformation during transmission. This hypothesis is backed by the fact that encoding and decoding works quite well and as expected when i omit transmission over the network as you can see in the following experiment.

Java script:
```
const protobuf = require('protobufjs');
const debug=require('debug')('usr');

run().catch(err => {
    debug('run: error')
    console.log(err)
});

async function run() {
    debug('run:...')

    const protoFile=__dirname+'/user.proto';
    debug('protofile: %s',protoFile)

    //async load of protobuf file
    const root = await protobuf.load(protoFile);
    const User = root.lookupType('userpackage.User');

    const dataPost = { name: 'Joe', age: 27, temperature: 36.7 };
    debug('data for POST: %s',JSON.stringify(dataPost))
    const encodedPost = User.encode(dataPost).finish();

    // Assume `req.body` contains the protobuf as a utf8-encoded string
    const user = User.decode(Buffer.from(encodedPost));
    debug('req.body decoded: %s',JSON.stringify(user));

} 
```

Result:
```
[nodemon] starting `node index.js`
  usr run:... +0ms
  usr protofile: /home/user/Desktop/sandbox/protobufjs/msg-usr/user.proto +3ms
  usr data for POST: {"name":"Joe","age":27,"temperature":36.7} +16ms
  usr req.body decoded: {"name":"Joe","age":27,"temperature":36.70000076293945} +8ms
[nodemon] clean exit - waiting for changes before restart
```

Anyhow, data transmission through the Internet is essential for my project. If anyone has a clue, please do not hesitate to point me in the right direction.

Cheers!

**Comment by dancesWithCycles** [comment]
Hi folks,
I want to share with you some results from my latest experiment with ```protobufjs```, ```node.js```, ```express.js``` and ```axios.js```.
I am getting closer to my target. I learned that the express server needs a body parser set to ```application/octet-stream```. I added the following code snippet:
```
var bodyParser = require('body-parser');
app.use(bodyParser.raw({type: 'application/octet-stream'}))
```
I do not know yet if it is necessary, but I added the ```binary``` argument when I am creating a Buffer. Here is an example:
```
Buffer.from(req.body,'binary'));
```
The final ```express.js``` server looks like this:
```
const express = require('express');
const protobuf = require('protobufjs');
const debug=require('debug')('xpress');

const app = express();
var bodyParser = require('body-parser');
app.use(bodyParser.raw({type: 'application/octet-stream'}))

run().catch(err => {
    debug('run error')
    console.log(err)
});

async function run() {

    const protoFile=__dirname+'/gtfs-realtime.proto';
    debug('protofile: %s',protoFile)
    
    //async load of protobuf file
    const root = await protobuf.load(protoFile);

    // Obtain message types
    const FeedMessage = root.lookupType("transit_realtime.FeedMessage");
    const FeedHeader = root.lookupType("transit_realtime.FeedHeader");
    const FeedEntity = root.lookupType("transit_realtime.FeedEntity");
    const VehiclePosition = root.lookupType("transit_realtime.VehiclePosition");
    const Position = root.lookupType("transit_realtime.Position");
    var pos = Position.create({latitude:36.1,longitude:79.1});
    debug('pos created')
    var vehiclePosition = VehiclePosition.create({position:pos});
    var feedEntity = FeedEntity.create({id:'uuid-xpress',
    vehicle:vehiclePosition});
    var feedHeader = FeedHeader.create({gtfsRealtimeVersion:'2.0',
    incrementality:0});
    var feedMessage = FeedMessage.create({header:feedHeader,
    entity:[feedEntity]});

    var encodedFeedMsg = FeedMessage.encode(feedMessage).finish();

    app.get('/user', function(req, res) {
	const bufferFeedMsg=Buffer.from(encodedFeedMsg,'binary');
	res.type('application/octet-stream').send(bufferFeedMsg);
    });
  
    app.post('/user', function(req, res) {
	const user = FeedMessage.decode(Buffer.from(req.body,'binary'));
	res.end();
    });
    await app.listen(3000);
} 
```
I still have problems to finally get the HTTP GET protobuf message through the network without encoding or transformation issues. The value for the longitude field is at the ```axios.js``` client not the same as at the ```express.js``` server. With correct encoding and networking however they ought to be the same.

Here is the server log msg:
```
[nodemon] starting `node index.js`
  xpress protofile: /home/user/Desktop/sandbox/protobufjs/express-msg-gtfs-rt/gtfs-realtime.proto +0ms
  xpress pos created +35ms
  xpress vehiclePosition created +2ms
  xpress feedEntity created +1ms
  xpress feedHeader created +1ms
  xpress feedMessage created +1ms
  xpress feedMessage JSON: {"header":{"gtfsRealtimeVersion":"2.0","incrementality":"FULL_DATASET"},"entity":[{"id":"uuid-xpress","vehicle":{"position":{"latitude":36.1,"longitude":79.1}}}]} +13ms
  xpress feedMessage valid +1ms
  xpress feedMessage encoded +2ms
  xpress encoded len: 38 +0ms
```

Here is the client log msg:
```
[nodemon] starting `node index.js`
  axios run:... +0ms
  axios protofile: /home/user/Desktop/sandbox/protobufjs/axios-msg-gtfs-rt/gtfs-realtime.proto +3ms
  axios data received via GET +73ms
  axios dataGet len: 38 +1ms
  axios dataBufferd len: 38 +0ms
  axios dataDecoded len: undefined +17ms
  axios decoded data in JSON: {"header":{"gtfsRealtimeVersion":"2.0","incrementality":"FULL_DATASET"},"entity":[{"id":"uuid-xpress","vehicle":{"position":{"latitude":36.099998474121094,"longitude":126.5999984741211}}}]} +1ms
```

You see, longitude has a value of 79.1  on the server side and 126.5999984741211 on the client side.

Here is the client code:
```
const axios = require('axios');
const protobuf = require('protobufjs');
const debug=require('debug')('axios');

run().catch(err => {
    debug('run: error')
    console.log(err)
});

async function run() {
    const protoFile=__dirname+'/gtfs-realtime.proto';
    const root = await protobuf.load(protoFile);
    const FeedMessage = root.lookupType("transit_realtime.FeedMessage");

    //HTTP GET
    let dataGet = await axios.get(
	'http://localhost:3000/user',
    	{
	    headers:{
		'accept':'application/octet-stream'}
	}
    )
	.then(res => res.data);

    const dataBuffered=Buffer.from(dataGet,'binary');
    const dataDecoded=FeedMessage.decode(dataBuffered);

    //HTTP POST
    const FeedHeader = root.lookupType("transit_realtime.FeedHeader");
    const FeedEntity = root.lookupType("transit_realtime.FeedEntity");
    const VehiclePosition = root.lookupType("transit_realtime.VehiclePosition");
    const Position = root.lookupType("transit_realtime.Position");
    var pos = Position.create({latitude:37.79192,longitude:-122.39087});
    var vehiclePosition = VehiclePosition.create({position:pos});
    var feedEntity=FeedEntity.create({id:'uuid-axios',vehicle:vehiclePosition});
    var feedHeader = FeedHeader.create({gtfsRealtimeVersion:'2.0',
    incrementality:0});
    var feedMessage = FeedMessage.create({header:feedHeader,entity:[feedEntity,feedEntity]});

    const encodedPost=FeedMessage.encode(feedMessage).finish();

    const res=await axios.post(
	'http://localhost:3000/user',
	encodedPost,
	{
	    headers:{
		'content-type':'application/octet-stream'}
	}
    ).then(res => res.data);

} 

```

I would be very thankful if anyone could point me in the right direction with the HTTP GET issue.

Cheers!

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
