### ISSUE TITLE
errorRangeError: index out of range: 3953 + 10 > 3953     at indexOutOfRange 

### ISSUE THREAD

**Issue by geetika-chugh** [protobufjs/protobuf.js#1615]
protobuf.js version: <please fill in>
6.8.4
<please describe the expected and actual behavior>

```js
<please provide a code snippet for reproduction>
```

```
<please paste the stack trace of the error if applicable>
```
wire format errorRangeError: index out of range: 3953 + 10 > 3953
    at indexOutOfRange (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/protobufjs/src/reader.js:13:12)
    at Reader.read_uint32 [as uint32] (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/protobufjs/src/reader.js:98:19)
    at Type.Duration$decode [as decode] (eval at Codegen (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:8:11)
    at Type.FlyItemComponentSlice$decode [as decode] (eval at Codegen (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:11:23)
    at Type.decode_setup [as decode] (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/protobufjs/src/type.js:507:25)
    at Type.FlyItemComponent$decode [as decode] (eval at Codegen (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:19:26)
    at Type.decode_setup [as decode] (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/protobufjs/src/type.js:507:25)
    at Type.FlyItem$decode [as decode] (eval at Codegen (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:29:33)
    at Type.decode_setup [as decode] (/Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/node_modules/protobufjs/src/type.js:507:25)
    at /Users/gchugh/FireFlyAutobotLatestCode/automationsvcs/test/sauce/PageObjectModels/FireFly/test.js:101:31

**Comment by geetika-chugh** [comment]
@dcodeIO Could you please help me i am really stuck

**Comment by alexander-fenster** [comment]
Hi @geetika-chugh, it would help if you show the proto file and the code that you run. It's hardly possible to figure out what's going on here without looking at the proto and the payload.  I would assume the payload does not match the schema.

**Comment by jschaf** [comment]
That error is from `uint32`. 

`r.pos` is at 3953 (the end of the buffer) when the error is thrown which means you have an unterminated varint. Probably a bad payload.

If I'm misunderstanding, it could be https://github.com/protobufjs/protobuf.js/pull/1380 but I don't think so.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
