### ISSUE TITLE
illegal token 'Int32Options'

### ISSUE THREAD

**Issue by jackqqxu** [protobufjs/protobuf.js#1617]
protobuf.js version: <please fill in>

<please describe the expected and actual behavior>

```js
ERROR: illegal token 'Int32Options', ';' expected (line 9)
  err: Error: illegal token 'Int32Options', ';' expected (line 9)
      at illegal (./node_modules/protobufjs/src/tokenize.js:124:16)
      at skip (./node_modules/protobufjs/src/tokenize.js:371:19)
      at parsePackage (./node_modules/protobufjs/src/parse.js:217:9)
      at Object.parse (./node_modules/protobufjs/src/parse.js:728:17)```

```
syntax = "proto2";
import "descriptor.proto";
package fable;

message Int32Options {
  optional int32 max = 1;
  optional int32 min = 2;
}
```

**Comment by VitalyName** [comment]
I guess. Is it typescript?

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
