### ISSUE TITLE
protoc-gen-validate validation rules produce parsing error

### ISSUE THREAD

**Issue by egamble** [protobufjs/protobuf.js#1644]
protobuf.js version: 6.11.2

We use `envoyproxy/protoc-gen-validate` to add validation rules to our protobuf files. One of these validation rules produces an error when the `.proto` file is parsed by protobuf.js:
```
message Foo {
  Bar bar = 1 [(validate.rules).enum = {not_in: [0]}];
}
```

When this message definition is parsed, an error is produced: `Error: illegal value '['`. This is referring to the `[0]` value  of `not_in: [0]`.

This is the stack trace:
```
at illegal (parse.js:96:16)
at readValue (parse.js:135:19)
at parseOptionValue (parse.js:606:33)
at parseOption (parse.js:585:27)
at parseInlineOptions (parse.js:638:17)
at parseField_line (parse.js:388:13)
at ifBlock (parse.js:294:17)
at parseField (parse.js:378:9)
at parseType_block (parse.js:350:21)
at ifBlock (parse.js:290:17)
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
