### ISSUE TITLE
Dependency errors with Yarn 2 Installation

### ISSUE THREAD

**Issue by angadn** [protobufjs/protobuf.js#1655]
protobuf.js version: 6.11.2

I am attempting to generate static sources using `pbjs` like so:

```
yarn add protobufjs@6.11.1
yarn run pbjs
```

This fails with the error

```
<workspace>/.pnp.cjs:59573
    throw firstError;
    ^

Error: protobufjs tried to access minimist, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: minimist
Required by: protobufjs@npm:6.11.2 (via <workspace>/.yarn/unplugged/protobufjs-npm-6.11.2-9b422ce98e/node_modules/protobufjs/cli/)

Require stack:
- <workspace>/.yarn/unplugged/protobufjs-npm-6.11.2-9b422ce98e/node_modules/protobufjs/cli/pbjs.js
- <workspace>/.yarn/unplugged/protobufjs-npm-6.11.2-9b422ce98e/node_modules/protobufjs/bin/pbjs
    at Function.external_module_.Module._resolveFilename (<workspace>/.pnp.cjs:59572:55)
    at Function.external_module_.Module._load (<workspace>/.pnp.cjs:59371:48)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (<workspace>/.yarn/unplugged/protobufjs-npm-6.11.2-9b422ce98e/node_modules/protobufjs/cli/pbjs.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.external_module_.Module._load (<workspace>/.pnp.cjs:59421:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

**Comment by angadn** [comment]
My current workaround in case it helps others

```
npm install -g protobufjs
pbjs
```

**Comment by alexander-fenster** [comment]
The yet-to-be-released v7 should fix this problem because the CLI tools are being moved to a separate package.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
