### ISSUE TITLE
protocolbuf.js fails to parse several schema of Google's protobuf repository

### ISSUE THREAD

**Issue by Conaclos** [protobufjs/protobuf.js#1709]
*protocolbuf.js* fails to parse several schema of [Google's protobuf repository](https://github.com/protocolbuffers/protobuf).

- [google/protobuf/util/message_differencer_unittest.proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/util/message_differencer_unittest.proto)

```
Error: illegal token 'map' (line 67)
```

- [google/protobuf/unittest.proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/unittest.proto)
- [google/protobuf/unittest_custom_options.proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/unittest_custom_options.proto)
- [google/protobuf/unittest_lite.proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/unittest_lite.proto)

```
TypeError: object must be a valid nested object
    at Namespace.add (protobufjs/src/namespace.js:222:15)
    at parseGroup (protobufjs/src/parse.js:452:16)
    at parseField (protobufjs/src/parse.js:360:13)
    at parseExtension_block (protobufjs/src/parse.js:735:25)
    at ifBlock (protobufjs/src/parse.js:290:17)
    at parseExtension (protobufjs/src/parse.js:722:9)
    at parseCommon (protobufjs/src/parse.js:273:17)
    at Object.parse (protobufjs/src/parse.js:790:21)
```

**Comment by notmedia** [comment]
Hi @alexander-fenster could you pay attention to this issue or ping appropriate maintainer please?

**Comment by timostamm** [comment]
Version 27.0 of google/protobuf added an extension with a group to [test_messages_proto2.proto](https://github.com/protocolbuffers/protobuf/blob/v27.0/src/google/protobuf/test_messages_proto2.proto#L259). 

Groups - especially in extensions - are probably very rarely used, but this file is required to run [conformance tests](https://github.com/protocolbuffers/protobuf/tree/main/conformance), so it's no longer possible to run proto2 tests with protobuf.js. See https://github.com/bufbuild/protobuf-conformance/pull/247.

**Comment by dcodeIO** [comment]
Thanks for the reports. The files listed above now parse correctly in v8.7.1. The proto2 edge case pinned down by @timostamm was fixed in v8.2.0.

In case the comparison repo linked above led you here, [see this fork](https://github.com/dcodeIO/protobuf-conformance) that tracks the same implementations at current versions and on equal test surface.
