### ISSUE TITLE
custom enum values proto fails loading

### ISSUE THREAD

**Issue by DianaSuvorova** [protobufjs/protobuf.js#1760]
protobuf.js version: 6.11.3

Fails while trying to load proto with custom enum values

proto line (complete [file](https://github.com/DianaSuvorova/test-protobufjs/blob/main/test.proto) to repro)

```
enum SideEffectTask {
 SIDE_EFFECT_TASK_INVALID = 0 [(descriptors) = {id: "SIDE_EFFECT_TASK_INVALID", name: "Invalid Task", type: TASK_TYPE_INVALID, entity_level: [REQUEST_ENTITY_INVALID]}];
 }

```

```js
const Protobuf = require('protobufjs');
const path = require('path');

const root = new Protobuf.Root();
const protoPath = path.join(__dirname, './test.proto');
const parsedProto = root.loadSync(protoPath);
```

```js
/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/root.js:104
            throw err;
            ^

Error: illegal value '[' (/Users/diana.suvorova/Dev/test-proto/test.proto, line 14)
    at illegal (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:96:16)
    at readValue (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:135:19)
    at parseOptionValue (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:606:33)
    at parseOption (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:585:27)
    at parseInlineOptions (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:638:17)
    at parseEnumValue_line (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:557:13)
    at ifBlock (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:294:17)
    at parseEnumValue (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:547:9)
    at parseEnum_block (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:532:15)
    at ifBlock (/Users/diana.suvorova/Dev/test-proto/node_modules/protobufjs/src/parse.js:290:17)
```

The repro repo: https://github.com/DianaSuvorova/test-protobufjs

**Comment by Bitencure** [comment]
+1 to this.

**Comment by andriuss** [comment]
Looking forward to this essential feature.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
