### ISSUE TITLE
Using `keepCase` option here would have helped in this example

### ISSUE THREAD

**Issue by troyatomic** [protobufjs/protobuf.js#1808]
I think this line in the example ... 

https://github.com/protobufjs/protobuf.js/blob/67fe5926da6dc5ed0ea04f0784f3bf8f19333cd5/README.md?plain=1#L233

should be changed to ...

```
protobuf.load("awesome.proto", { keepCase: true}, function(err, root) { // keepCase is needed since snake_case property is used
```

since the example uses snake_case fields.

Either that or change the example not to use snake_case properties and instead use camelCase as the style guide recommends.  But if you do this, then please mention the `keepCase` option as it is needed if BigQuery fields use snake_case.

**Comment by neilyoung** [comment]
Hmm. That ends up in 

```
index-light.js:29 Uncaught TypeError: root.load is not a function
    at Object.load (index-light.js:29:1)
    at script.js:1:10
```

here. Using

```
<script src="//cdn.jsdelivr.net/npm/protobufjs@7.X.X/dist/protobuf.js"></script>

```

What version are u using?

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
