### ISSUE TITLE
Extra semicolon causes silent parsing failures during proto file load

### ISSUE THREAD

**Issue by josephharrington** [protobufjs/protobuf.js#1818]
protobuf.js version: `protobufjs-cli@1.0.2`

If an imported proto file contains a double semicolon, `;;`, then it will cause silent parsing failures. This causes very difficult-to-debug errors around missing messages.

An improvement would be for the error message to reference the offending line with the double semicolon. A true fix would be to accept double semicolon as valid syntax. A double semicolon should be valid as defined by `emptyStatement` in the [proto3 grammar](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#proto_file). It is accepted by the `protoc` compiler.

There is another similar issue #1322, but the error message I've mentioned below is much worse because it does not point out the offending line (which may be very far away from the missing message mentioned in the error). Noticing an extra semicolon in a large proto file is nearly impossible unless you know what you're looking for.

### Reproduction:

```proto
// main.proto
syntax = "proto3";
package main;
import "other.proto";

message MainMessage {
  main.OtherMessage description = 1;
}
```
```proto
// other.proto
syntax = "proto3";
package main;; // double semicolon

message OtherMessage {
  int64 value = 1;
}
```

### Steps:
1. Create the above two files, `main.proto` and `other.proto`.
2. Run `pbjs main.proto`.

### Error:
```
./node_modules/protobufjs-cli/pbjs.js:251
            throw err;
            ^

Error: no such Type or Enum 'main.OtherMessage' in Type .main.MainMessage
    at Type.lookupTypeOrEnum (./node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (./node_modules/protobufjs/src/field.js:268:94)
    at Type.resolveAll (./node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (./node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (./node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (./node_modules/protobufjs/src/root.js:258:43)
    at Object.main (./node_modules/protobufjs-cli/pbjs.js:242:48)
    at Object.<anonymous> (./node_modules/protobufjs-cli/bin/pbjs:4:16)
```

**Comment by josephharrington** [comment]
We ran into another syntax that causes a similar issue:
```proto
  rpc sayHello(HelloRequest) returns (HelloReply) {
    option (internal.company.docs) = {
      description: "This is a string with a semicolon after it";
    };
  }
```

If the semicolon is present after the field value, it will cause a silent parsing failure at runtime when the proto file is loaded.

These parsing failures result in the remainder of the proto file after the offending syntax essentially being silently discarded, and only manifest as missing type errors later in the parsing flow when those discarded types are referenced.

**Comment by josephharrington** [comment]
Actually I tested this with latest protobufjs (7.4.0) and I think this is fixed! The double semicolon now gets an illegal token error (which I don't think is fully correct based on the grammar, but is a massive improvement) and I cannot reproduce the option field issue I commented about earlier today. I'll close this for now.
