### ISSUE TITLE
protobufjs: v7.1.2 protobufjs-cli: v1.0.2 using pbjs to generate errors

### ISSUE THREAD

**Issue by df-songyu** [protobufjs/protobuf.js#1836]
My generated code is

```cpp
node_modules/.bin/pbjs --no-create --no-verify --no-convert --no-delimited --force-long --force-message -t static-module -w commonjs -o {_src_dir}/ message.js *.proto
```

Error message after execution

```cpp
D:\XXX\node_modules\protobufjs-cli\pbjs.js:251
throw err;
^

Error: unresolvable extensions: 'extend google.protobuf.EnumValueOptions' in .msg, 'extend google.protobuf.MethodOptions' in .msg, 'extend google.protobuf.MethodOptions' in .msg, 'extend google.protobuf.MethodOptions' in .msg, 'extend google.protobuf.MethodOptions' in .msg
at Root.resolveAll (D:\XXX\node_modules\[4mprotobufjs[24m\src\root.js:255:15)
at Object.main (D:\XXX\node_modules\[4mprotobufjs-cli[24m\pbjs.js:242:48)
at Object.<anonymous> (D:\XXX\node_modules\[4mprotobufjs-cli[24m\bin\pbjs:4:16)
[90m    at Module._compile (node:internal/modules/cjs/loader:1155:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:1033:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:868:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m
[90m    at node:internal/main/run_main_module:22:47[39m
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
