### ISSUE TITLE
Fails to parse "{" in options

### ISSUE THREAD

**Issue by kpritam-tw** [protobufjs/protobuf.js#1878]
protobuf.js version: 1.1.1

Fails to parse following option

```js

option (scalapb.options) = {
  field_transformations: [
    {
      when: {options: {[validate.rules] {message: {required: true}}}}
      set: {
        [scalapb.field] {
          required: true
        }
      }
    }
  ]
};
```

```
usr/local/lib/node_modules/protobufjs-cli/pbjs.js:254
            throw err;
            ^

Error: illegal value '{' (../target/x.proto, line 15)
    at illegal (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/parse.js:96:16)
    at readValue (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/parse.js:135:19)
    at parseOptionValue (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/parse.js:630:41)
    at parseOption (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/parse.js:600:27)
    at parse (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/parse.js:822:17)
    at process (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/root.js:127:30)
    at fetch (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/root.js:179:13)
    at Root.load (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/root.js:207:13)
    at Root.loadSync (/usr/local/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/root.js:248:17)
    at Object.main (/usr/local/lib/node_modules/protobufjs-cli/pbjs.js:245:18)

Node.js v19.8.1
```

**Comment by marsh73** [comment]
Is there a reason that this is not being addressed? In earlier versions it was the the "[" that threw the error. But this is valid proto definition https://protobuf.com/docs/language-spec#resolving-option-names

**Comment by marsh73** [comment]
from the protobufjs docs on resolving optional names, here is an example that i don't see captured in your tests... 

`option (google.api.http) = {
    custom: {
        kind: "FETCH"
        path: "/foo/bar/baz/{id}"
    }
    additional_bindings: [
      {
          get: "/foo/bar/baz/{id}"
      },
      {
          post: "/foo/bar/baz/"
          body: "*"
      }
    ]
};`

previously, this threw an error for the `[` being present. Now that is fixed, but it doesn't seem to like the '{' inside the '['.

`Error: illegal value '{'`

**Comment by marsh73** [comment]
@kpritam-tw did you ever find a solution? I have only been able to get it working by refactoring my proto definitions to use the original verbose format for declaring multiple option names

**Comment by kpritam-tw** [comment]
> @kpritam-tw did you ever find a solution? I have only been able to get it working by refactoring my proto definitions to use the original verbose format for declaring multiple option names

Not really, the workaround is to move that piece of configuration in `package.proto` file. In that case, scala applies those configurations and on the `js` side, you can parse the file without `package.proto`

**Comment by marsh73** [comment]
i think the problem is that i'm consuming proto source files from a backend service i don't own... so i can't just move files around. using those files more as a contract for the service itsefl

**Comment by Kanade-Lu** [comment]
same problem。my error code as follow

```
  // 排序条件
  string order_by = 5 [(lixin.common.validator.v1.order) = {
    object: "car_series",
    rules: [
      {field: "id"},
      {field: "display_name"}]
  }];

```


```
/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/root.js:102
            throw err;
            ^

Error: illegal value '{' (/Users/rim/Documents/work/my-vitesse-app/protobuf/lixin/dos/store/v1/msg_car.proto, line 142)
    at illegal (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:96:16)
    at readValue (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:135:19)
    at parseOptionValue (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:664:41)
    at parseOption (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:631:27)
    at parseInlineOptions (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:711:17)
    at parseField_line (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:419:13)
    at ifBlock (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:315:17)
    at parseField (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:409:9)
    at parseType_block (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:371:21)
    at ifBlock (/Users/rim/Library/pnpm/global/5/.pnpm/protobufjs@7.4.0/node_modules/protobufjs/src/parse.js:311:17)
```
