### ISSUE TITLE
Decoding fails sometimes, logs attached

### ISSUE THREAD

**Issue by dazhbog** [protobufjs/protobuf.js#1917]
protobuf.js version: 6 and 7

I have some packets (raw bytes) that succeed fine in python and C but fail in protobufjs. File 1 succeeds, File 2 fails (the raw bytes are shown in Example 1 and 2). I suspect its something with the end of the buffer and the uint32 parsing., but the crc32 succeeds on both packets and the other libraries dont have an issue.

Please see code, trace and attached proto files that I tried

```js
var binaryData = fs.readFileSync("./file.dat")
var protobuf = require('protobufjs');              
var InitCommand = protobuf.loadSync('./dfu-cc3.proto').lookupType('InitCommand');
var obj = InitCommand.toObject(InitCommand.decode(binaryData), {
           longs: String,  // Convert longs to strings (if any)
           enums: String,  // Convert enums to strings (if any)
           bytes: String,  // Convert bytes to base64 encoded strings (if any)
           json: true     // This flag will output plain JSON objects
});
```
```
EXAMPLE 1 OK
Reading dat file.. Done, length: 141 CRC: C95A844A
12 8A 01 0A 44 08 01 12 40 08 04 10 34 1A 02 CA 01 20 00 28 00 30 00 38 D0 F7 13 42 24 08 03 12 20 3C 65 48 1E F6 99 71 D1 5D F3 FF E5 4C 0E 98 4F FD B7 DC 3A 22 CA DE 6E 63 F6 5B 14 56 AC A0 77 48 00 52 04 08 01 12 00 10 00 1A 40 53 98 07 DE 06 DD A4 C8 77 DD 5C 27 8C 5D 78 A7 76 58 0B 56 2D 90 14 91 7B B8 91 FE 18 8A 0B AC 20 39 95 49 16 89 96 A8 CC 4C AB 9D 77 E3 56 DA FB 98 75 76 47 31 96 4F 1B B0 58 DC A4 A0 21 45

.dat file looks good!
```
```
EXAMPLE 2 FAILS (i think uint32 read at position 139 starts going out of bounds)
Reading dat file.. Done, length: 141 CRC: 19D7C0C6
12 8A 01 0A 44 08 01 12 40 08 04 10 34 1A 02 CA 01 20 00 28 00 30 00 38 B0 EE 13 42 24 08 03 12 20 76 81 E0 B7 4D 32 1F 1F E3 E8 23 5E CF EF 3C BB F0 14 F9 2E 02 DE 08 C7 30 43 A0 C5 AF FE 23 B5 48 00 52 04 08 01 12 00 10 00 1A 40 E6 96 0A 3E 9D 87 A8 9D 19 32 38 A1 9D 8E CC 15 2D 48 0B E1 34 E1 1B 66 4D 70 22 F6 97 E9 F2 EA C1 20 28 3F 05 52 AE 55 60 1F 31 1A 5E 48 0D 0F 7E 5E 2A E0 CF 84 28 80 32 04 51 10 B4 2C 9E B4
/mnt/c/Users/TEST/node_modules/protobufjs/src/reader.js:108
            throw indexOutOfRange(this, 10);
            ^

RangeError: index out of range: 141 + 10 > 141
    at indexOutOfRange (/mnt/c/Users/TEST/node_modules/protobufjs/src/reader.js:13:12)
    at BufferReader.read_uint32 [as uint32] (/mnt/c/Users/TEST/node_modules/protobufjs/src/reader.js:108:19)
    at Type.InitCommand$decode [as decode] (eval at Codegen (/mnt/c/Users/TEST/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:22:18)
    at Type.decode_setup [as decode] (/mnt/c/Users/TEST/node_modules/protobufjs/src/type.js:507:25)
    at Object.<anonymous> (/mnt/c/Users/TEST/zipprocessor.js:143:60)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

_Attached .proto files, renamed to txt for github_
[dfu-cc3.proto.txt](https://github.com/protobufjs/protobuf.js/files/12269224/dfu-cc3.proto.txt)
[dfu-cc.proto.txt](https://github.com/protobufjs/protobuf.js/files/12269225/dfu-cc.proto.txt)

**Comment by dazhbog** [comment]
ok nevermind, I was decoding the wrong sub-message _InitCommand_. I should have decoded the _Packet_ message.. Closing
