### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by mqzhifu** [protobufjs/protobuf.js#1920]
RangeError: index out of range: 3 + 99 > 38
    at indexOutOfRange (D:\nodejs\zjsframework\node_modules\protobufjs\src\reader.js:13:12)
    at Reader.skip (D:\nodejs\zjsframework\node_modules\protobufjs\src\reader.js:338:19)
    at Reader.skipType (D:\nodejs\zjsframework\node_modules\protobufjs\src\reader.js:364:18)
    at Reader.skipType (D:\nodejs\zjsframework\node_modules\protobufjs\src\reader.js:368:22)
    at Type.LoginRes$decode [as decode] (eval at Codegen (D:\nodejs\zjsframework\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:23:5)
    at Type.decode_setup [as decode] (D:\nodejs\zjsframework\node_modules\protobufjs\src\type.js:507:25)

上面是错误信息，.proto 如下：

message LoginRes{
    int32   code        = 1;
    int32   uid         = 2;
    string  err_msg     = 3;
}

问题 是： err_msg      只要设置值，就报错，如果不设置此值，就成功

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
