### ISSUE TITLE
"Invalid wire type n" "index out of range: n + 1 > n"

### ISSUE THREAD

**Issue by KiillThemAll** [protobufjs/protobuf.js#1927]
protobuf.js version: 7.2.4
imported node module

Different errors on decode by pbjs in case of uint64 value with tags 2 or 3 or 4. With other tags everything is fine.
!Data is sent in binary everywhere and remains the same!
Suppose, something with decoding procedure.
Errors:
"Invalid wire type n"
"index out of range: n + 1 > n"

This error have been mentioned in other issues, but in other circumstances and no clues so far.
#987 
#1297 
#907 
#991
#1049 
#1063 
and others

To reproduce:

Proto message:
```
message PlaceAction{
  uint64 place_id = 1;
  string action = 2;
  string url = 3;
  uint64 city_id = 4;
}
```

Generate by pbjs with long!

Generated decode func:
```
PlaceAction.decode = function decode (reader, length) {
      if (!(reader instanceof $Reader)) { reader = $Reader.create(reader); }
      let end = length === undefined ? reader.len : reader.pos + length; let message = new $root.object_msg.PlaceAction();
      while (reader.pos < end) {
        let tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            message.place_id = reader.uint64();
            break;
          }
          case 2: {
            message.action = reader.string();
            break;
          }
          case 3: {
            message.url = reader.string();
            break;
          }
          case 4: {
            message.city_id = reader.uint64();
            break;
          }
          default:
            reader.skipType(tag & 7);
            break;
        }
      }
      return message;
    };
```

Example stack trace:

index out of range: 18 + 1 > 18
RangeError: index out of range: 18 + 1 > 18
    at indexOutOfRange (http://localhost:8080/js/chunk-vendors.js:17476:12)
    at Reader.skip (http://localhost:8080/js/chunk-vendors.js:17807:23)
    at push../node_modules/protobufjs/src/reader.js.Reader.skipType (http://localhost:8080/js/chunk-vendors.js:17821:18)
    at Function.decode (http://localhost:8080/js/app.js:5454:20)
    at Function.decode (http://localhost:8080/js/app.js:5586:63)

**Comment by KiillThemAll** [comment]
Incremented city_id tag to 5 and everything works as expected. But this is bad solution.

**Comment by alexander-fenster** [comment]
Oh wow, that must be a cool bug somewhere. I will try to figure out what's going on, thank you!

**Comment by KiillThemAll** [comment]
Looking forward to your investigation, such errors could lead to extremely unpredictable behaviour.

**Comment by KiillThemAll** [comment]
Another recent issue:
#1920

**Comment by UCoyote** [comment]
I had the same problem。Change the data type to uint32 and everything works as expected

**Comment by pine-serpent** [comment]
i have this issue in my mollysocket docker container:

[2024-10-28T03:57:36Z ERROR mollysocket::ws::websocket_connection] Failed to decode protobuf: failed to decode Protobuf message: invalid wire type value: 7
[2024-10-28T03:57:36Z WARN  mollysocket::ws::websocket_connection] Websocket finished

how can i apply the above fix for this?

thank you for any help you can provide.

**Comment by KiillThemAll** [comment]
@pine-serpent 
Just do not use int64 and uint64 with tags 2, 3, 4

**Comment by KiillThemAll** [comment]
> Oh wow, that must be a cool bug somewhere. I will try to figure out what's going on, thank you!

@alexander-fenster 
Any clues? 
Really old and annoying bug. 
We have to skip these tags in production project every time...

**Comment by JungminByun** [comment]
protobuf.js version: 7.4.0

It keeps printing the message "invalid wire type 6"
Protobuf is created as uint64 and the type cannot be changed

How do I solve this?
Has anyone solved it?

**Comment by KiillThemAll** [comment]
@JungminByun 
Just do not use int64 and uint64 with tags 2, 3, 4
Its the only solution that works

**Comment by KiillThemAll** [comment]
Living with this for 1,5 year...

**Comment by JungminByun** [comment]
@KiillThemAll 
I saw above that you should not use int64 and uint64 with tags 2, 3, 4.
I did not create the data, the data is already defined that way. (int64 and uint64 with tags 2, 3, 4.)
Is there a workaround for this?

For example, is it okay to change tags?

[AS IS]
message Road {
int32 seq = 1;
uint64 linkLength = 2;
uint64 linkID = 3;
}

[TO BE]
message Road {
int32 seq = 1;
uint64 linkLength = 5;
uint64 linkID = 6;
}

**Comment by dcodeIO** [comment]
There was one adjacent reader bug fixed in 8.6.3 (#2322), where truncated 64-bit varints could be partially accepted instead of rejected consistently. That could indirectly have produced errors like `invalid wire type` or `index out of range`, but is not necessarily the exact issue in question here. Other than that, I cannot reproduce this issue with valid protobuf wire data in current versions.

Hence closing. If this still reproduces, having the exact byte array, schema, and generator options would be helpful.
