### ISSUE TITLE
npm ERR! The "file" argument must be of type string

### ISSUE THREAD

**Issue by OriginalStefikO** [protobufjs/protobuf.js#1935]
protobuf.js version: v7.2.5
node version: v18.17.1
npm version: v10.1.0

I'm trying to install protobuf using "npm install protobufjs" and it gives this error:
```
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "file" argument must be of type string. Received undefined
```

Log
```
297 info run protobufjs@7.2.5 postinstall node_modules/protobufjs node scripts/postinstall
298 info run protobufjs@7.2.5 postinstall { code: undefined, signal: undefined }
299 verbose stack TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
299 verbose stack     at new NodeError (node:internal/errors:405:5)
299 verbose stack     at validateString (node:internal/validators:162:11)
299 verbose stack     at normalizeSpawnArguments (node:child_process:545:3)
299 verbose stack     at spawn (node:child_process:750:13)
299 verbose stack     at C:\Users\Admin\AppData\Roaming\nvm\v18.17.1\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:18:12
299 verbose stack     at new Promise (<anonymous>)
299 verbose stack     at promiseSpawn (C:\Users\Admin\AppData\Roaming\nvm\v18.17.1\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:17:13)
299 verbose stack     at spawnWithShell (C:\Users\Admin\AppData\Roaming\nvm\v18.17.1\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:123:10)
299 verbose stack     at promiseSpawn (C:\Users\Admin\AppData\Roaming\nvm\v18.17.1\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
299 verbose stack     at runScriptPkg (C:\Users\Admin\AppData\Roaming\nvm\v18.17.1\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:79:13)
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
