### ISSUE TITLE
Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by justaguyin2k23** [protobufjs/protobuf.js#1958]
protobuf.js version: 7.2.5
gprc-js version 1.9.13
proto-loader version 0.7.10

line #488 of [protobuf.js/ext/descriptor/index.js] 

    if ((descriptor.oneofIndex = this.parent.oneofsArray.indexOf(this.partOf)) < 0)
            throw Error("missing oneof");

causes the error **Cannot read properties of undefined (reading 'indexOf')** when calling proto-loader's  loadPackageDefinition function. 

```js
const proto = grpc.loadPackageDefinition(packageDefinition);
```

This specifically happens when the latest version of buf/validate.proto is among the proto files being used.

Changing line #488 to below solves the issue, 

if ((**this.parent.oneofsArray &&** descriptor.oneofIndex = this.parent.oneofsArray.indexOf(this.partOf)) < 0)

Stacktrace
```
From Node.js Internals:
  TypeError: Cannot read properties of undefined (reading 'indexOf')
      at Field.toDescriptor (/Users/tiredcoder/dev/cncp/cncp-apis/cypress-tests/node_modules/protobufjs/ext/descriptor/index.js:488:62)
      at Root_toDescriptorRecursive (/Users/tiredcoder/dev/cncp/cncp-apis/cypress-tests/node_modules/protobufjs/ext/descriptor/index.js:142:40)
      at Root_toDescriptorRecursive (/Users/tiredcoder/dev/cncp/cncp-apis/cypress-tests/node_modules/protobufjs/ext/descriptor/index.js:146:13)
      at Root_toDescriptorRecursive (/Users/tiredcoder/dev/cncp/cncp-apis/cypress-tests/node_modules/protobufjs/ext/descriptor/index.js:146:13)
      at Root.toDescriptor (/Users/tiredcoder/dev/cncp/cncp-apis/cypress-tests/node_modules/protobufjs/ext/descriptor/index.js:121:5)
      at createPackageDefinition (/Users/tiredcoder/dev/cncp/cncp-apis/cypress-tests/node_modules/@grpc/proto-loader/src/index.ts:327:66)
      at Object.loadSync (/Users/tiredcoder/dev/cncp/cncp-apis/cypress-tests/node_modules/@grpc/proto-loader/src/index.ts:392:10)
 
     at createService (/Users/tiredcoder/dev/cncp/cncp-apis/cypress-tests/cypress.config.ts:38:49)
 ```
I see a somewhat similar issue, https://github.com/protobufjs/protobuf.js/issues/1898 but no resolution.

**Comment by josephharrington** [comment]
We ran into this same issue. It seems to occur when an `extend` has an `optional` field, e.g,:
```proto
extend google.protobuf.FieldOptions {
  optional NfTrackerInfo nfTrackerInfo = 50001;
}
```

I see the original report above mentions `buf/validate.proto` which has similar `extend` patterns.

**Comment by josephharrington** [comment]
Here is a minimal repro of the issue:

```proto
// extend.proto
syntax = "proto3";

message SomeMessage {
  string foo = 1;
}

extend SomeMessage {
  optional string bar = 2;
}
```

```js
// index.mjs
import protobufjs from 'protobufjs';
import descriptor from 'protobufjs/ext/descriptor/index.js';
import path from 'path';

const dirname = path.dirname(new URL(import.meta.url).pathname);

const root = protobufjs.loadSync(path.join(dirname, 'extend.proto'));
root.toDescriptor('proto3').file;
```

And the error:
```
./node_modules/protobufjs/ext/descriptor/index.js:488
        if ((descriptor.oneofIndex = this.parent.oneofsArray.indexOf(this.partOf)) < 0)
                                                             ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Field.toDescriptor (./node_modules/protobufjs/ext/descriptor/index.js:488:62)
    at Root_toDescriptorRecursive (./node_modules/protobufjs/ext/descriptor/index.js:142:40)
    at Root.toDescriptor (./node_modules/protobufjs/ext/descriptor/index.js:121:5)
    at file:///./index.mjs:8:6
```

**Comment by josephharrington** [comment]
FWIW it looks like the reason the existing tests do not hit this issue is because `tests/data/test.proto` is proto2 instead of proto3. If I change that proto file to proto3 then the tests start failing with this exact issue.
