### ISSUE TITLE
pbjs gives "Error: duplicate name 'Http' in Namespace .google.api"

### ISSUE THREAD

**Issue by cusher** [protobufjs/protobuf.js#1970]
protobuf.js version: 7.2.6 (cli version: 1.1.2)

With previous versions, including 7.2.5, building many proto files into a single bundle with pbjs/pbts works without issue, e.g.:
```
node_modules/protobufjs-cli/bin/pbjs -p ../../ $protofiles --keep-case -w commonjs -t json-module -o src/app/proto-reflection.js
```

With version 7.2.6 installed, this now gives an error:
```
/projectdir/node_modules/protobufjs-cli/pbjs.js:254
            throw err;
            ^

Error: duplicate name 'Http' in Namespace .google.api
    at Namespace.add (/projectdir/node_modules/protobufjs/src/namespace.js:239:23)
    at parseType (/projectdir/node_modules/protobufjs/src/parse.js:354:16)
    at parseCommon (/projectdir/node_modules/protobufjs/src/parse.js:261:17)
    at parse (/projectdir/node_modules/protobufjs/src/parse.js:842:21)
    at process (/projectdir/node_modules/protobufjs/src/root.js:127:30)
    at fetch (/projectdir/node_modules/protobufjs/src/root.js:179:13)
    at process (/projectdir/node_modules/protobufjs/src/root.js:133:29)
    at fetch (/projectdir/node_modules/protobufjs/src/root.js:179:13)
    at process (/projectdir/node_modules/protobufjs/src/root.js:133:29)
    at fetch (/projectdir/node_modules/protobufjs/src/root.js:179:13)
```

**Comment by tanrich** [comment]
Using node18 can solve the problem. I just stepped into a pit today...

**Comment by cusher** [comment]
I finally took some time to dig into what was going wrong here and was able to get past the 7.2.5 -> 7.2.6 bump.

A couple of hints in case anyone else runs into this problem:
- You should *not* be including the google proto files in your list of proto files being compiled (I think this was needed at one point due to a regression that was later fixed).
- You *should* pass in each proto base directory in your project with `-p` flags if your proto files have imports from multiple directories. For some reason this was not necessary prior to 7.2.6.
