### ISSUE TITLE
Editions Suport

### ISSUE THREAD

**Issue by Jde-cpp** [protobufjs/protobuf.js#1976]
protobuf.js version: 7.2.6

Expected:  compile source  with editions https://protobuf.dev/editions/overview/
Actual: Fails.

```protobuf
edition = "2023";
message Player {}
```

```
Error: illegal token 'edition' (Player.proto, line 8)
    at illegal (/usr/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/parse.js:96:16)
    at parse (/usr/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/parse.js:820:23)
    at process (/usr/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/root.js:127:30)
    at fetch (/usr/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/root.js:178:13)
    at Root.load (/usr/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/root.js:206:13)
    at Root.loadSync (/usr/lib/node_modules/protobufjs-cli/node_modules/protobufjs/src/root.js:247:17)
```

**Comment by dcodeIO** [comment]
In current versions, editions 2023/2024 are supported.
