### ISSUE TITLE
this.isZero is not a function using int64 and strings

### ISSUE THREAD

**Issue by yagop** [protobufjs/protobuf.js#925]
protobuf.js version: 6.8.0
nodejs version: 8.5.0

I'm getting the following error when using `console.log('%j', msg)` on a `int64` value assigned by string. When assigned from a number it works. int64 is not supposed to be assigned from string?

```js
const protobuf = require("protobufjs");

const proto = `
package main;

message Foo {
  optional int64 id = 1;
}
`

const root = protobuf.parse(proto).root;

const Foo = root.lookupType('main.Foo');

const foo = Foo.create({
  id: '1234'
});

foo.toJSON();

```

Error:
```bash
node proto.js 
/tmp/node_modules/long/dist/long.js:497
        if (this.isZero())
                 ^

TypeError: this.isZero is not a function
    at String.toString (/tmp/node_modules/long/dist/long.js:497:18)
    at Type.Foo$toObject [as toObject] (eval at Codegen (/tmp/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:18:57)
    at Type.toObject (/tmp/node_modules/protobufjs/src/type.js:570:25)
    at Foo.toJSON (/tmp/node_modules/protobufjs/src/message.js:136:23)
    at Object.<anonymous> (/tmp/proto.js:19:5)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by dcodeIO** [comment]
Try using `Message.fromObject` instead of `.create` ([see](https://github.com/dcodeIO/protobuf.js#toolset)).

**Comment by yagop** [comment]
Thanks, with `Message.fromObject` works.

You can close the issue if so.
