### ISSUE TITLE
pbjs import error

### ISSUE THREAD

**Issue by changyuan79** [protobufjs/protobuf.js#989]
protobuf.js version: <6.8.5>

I need to use protobuf.js pbjs command line tool to convert a number of protos to a JSON file. The proto files are located in different directories like this:
schema/path_a/a.proto
schema/path_b/b.proto

Inside "b.proto", I import "a.proto" and use its definition like this:
`import a.proto;
...
path_a.type_a a;`

I used the pbjs command line tool like this:
```js
node_modules/protobufjs/bin/pbjs -t json -r ~/schema -p ~/schema/path_a -p ~/schema/path_b ~/schema/path_b/b.proto > bundle.json
```

I got the following error message:
```
Error: no such Type or Enum 'schema.path_a.type_a' in Type schema.path_a.a
    at Type.lookupTypeOrEnum (app/node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (app/node_modules/protobufjs/src/field.js:265:94)
    at Type.resolveAll (app/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (app/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (app/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (app/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (app/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (app/node_modules/protobufjs/src/root.js:246:43)
    at Object.main (app/node_modules/protobufjs/cli/pbjs.js:226:48)
    at Object.<anonymous> (app/node_modules/protobufjs/bin/pbjs:4:16)
```

Any hints on how to import the dependencies correctly and package them into one single JSON file using protobufjs pbjs tool? Thank you!

**Comment by sharyu** [comment]
Also meet this issue in version 6.8.6. Hope devs can solve this...

**Comment by benesch** [comment]
Ran into this recently and it turns out the issue was actually caused by a swallowed syntax error. If that's indeed the case for you too, #1050 will at least surface the error. In our case it was a double semicolon which was trivial to fix.

**Comment by changyuan79** [comment]
obsolete.
